package wrapper;

import javafx.scene.layout.BorderPane;
import javafx.fxml.FXMLLoader;
import db.entity.*;
import adapter.base.ControlAdapter;
import java.util.HashSet;
import widgets.table.Table;
import application.Main;
import controls.*;
import annotations.AutoGenerated;
import java.util.HashMap;
import javafx.scene.Parent;
import sceneswitch.SceneBase;
import java.util.Map;
import java.util.Collection;
import table.MfTable;
import widgets.table.*;
import client.IClient;

import javafx.scene.Scene;
import javafx.scene.control.*;
import action.*;
import db.interfaces.IEntity;
import javafx.scene.image.ImageView;
import java.util.Set;
import javafx.scene.text.Text;

@AutoGenerated
public class CustomerCharacterizationReportScreen extends SceneBase {

	public CustomerCharacterizationReportScreen(ISceneSwitcher sceneSwitcher, IClient client) throws Exception {
		super(sceneSwitcher, client);
		initialize();
	}

	public void initialize() throws Exception {
		Parent root = FXMLLoader.load(Main.class.getResource("CustomerCharacterizationReportScreen.fxml"));
		_scene = new Scene(root);

		//scene switchers
		MfImageView mainMenuMarketingScreenControl = new MfImageView((ImageView) _scene.lookup("#scene$MainMenuMarketingScreen"));
		mainMenuMarketingScreenControl.addEvent((event) -> { _switcher.switchScene("MainMenuMarketingScreen"); });

		MfImageView customersManagementScreenControl = new MfImageView((ImageView) _scene.lookup("#scene$CustomersManagementScreen"));
		customersManagementScreenControl.addEvent((event) -> { _switcher.switchScene("CustomersManagementScreen"); });

		//entities instantiation
		Customer customer = new Customer();
		Car car = new Car();
		FuelingPurchase fuelingPurchase = new FuelingPurchase();

		//entities assignments
		car.setCustomer(customer);
		fuelingPurchase.setCar(car);
		fuelingPurchase.setCustomer(customer);

		//controls instantiation
		MfDatePicker dateTimeControlTo = new MfDatePicker((DatePicker) _scene.lookup("#table$customer$car$fueling_purchase$date_time$$$to"));
		MfDatePicker dateTimeControlFrom = new MfDatePicker((DatePicker) _scene.lookup("#table$customer$car$fueling_purchase$date_time$$$from"));

		//tables instantiation
		BorderPane fuelingPurchaseBp = (BorderPane) _scene.lookup("#uitable$noneditable$single$fueling_purchase");
		Table<FuelingPurchase> fuelingPurchaseTableWrapper = new Table<FuelingPurchase>();
		MfTable<FuelingPurchase> fuelingPurchaseTable = new MfTable<FuelingPurchase>(FuelingPurchase.class);
		fuelingPurchaseTable.setEditable(false);
		MfSingleDecorator<FuelingPurchase> fuelingPurchaseSingleDecorator = new MfSingleDecorator<FuelingPurchase>();
		fuelingPurchaseTableWrapper.addDecorator(fuelingPurchaseSingleDecorator);
		fuelingPurchaseTableWrapper.setTable(fuelingPurchaseTable);
		fuelingPurchaseBp.setCenter(fuelingPurchaseTable);

		//initializations
		MfImageView filterFuelingPurchaseControl = new MfImageView((ImageView) _scene.lookup("#action$collect$fueling_purchase"));
		ActionControl fuelingPurchasefilterAction = new ActionControl();
		fuelingPurchasefilterAction.setControl(filterFuelingPurchaseControl);
		FilterCapability fuelingPurchaseFilterCapability = new FilterCapability();
		fuelingPurchaseFilterCapability.setQueryEntities(prepareQuery(fuelingPurchase));
		fuelingPurchasefilterAction.addCapability(fuelingPurchaseFilterCapability);
		fuelingPurchasefilterAction.setClient(_client);
		fuelingPurchasefilterAction.setCallback((response) -> {
			Collection<IEntity> entities = response.getEntities();
			for (IEntity ientity : entities) {
				FuelingPurchase entity = (FuelingPurchase) ientity;
			}
		});

		//fields initializations
		dateTimeControlTo.setField(fuelingPurchase.getClass().getDeclaredField("_date_time"));
		dateTimeControlTo.setEntity(fuelingPurchase);

		dateTimeControlFrom.setField(fuelingPurchase.getClass().getDeclaredField("_date_time"));
		dateTimeControlFrom.setEntity(fuelingPurchase);

		//grouping
		groupControls(new ControlAdapter[] { dateTimeControlTo, dateTimeControlFrom });

	}
	private Map<IEntity, Map<String, String>> prepareQuery(FuelingPurchase fuelingPurchase) {
		Map<IEntity, Map<String, String>> map = new HashMap<IEntity, Map<String, String>>();
		
		Map<String, String> queryMap = new HashMap<String, String>();
		
		map.put(fuelingPurchase, queryMap);
		return map;
	}
}
