package wrapper;

import javafx.scene.layout.BorderPane;
import javafx.fxml.FXMLLoader;
import db.entity.*;
import adapter.base.ControlAdapter;
import java.util.HashSet;
import widgets.table.Table;
import application.Main;
import controls.*;
import annotations.AutoGenerated;
import java.util.HashMap;
import javafx.scene.Parent;
import sceneswitch.SceneBase;
import java.util.Map;
import java.util.Collection;
import table.MfTable;
import widgets.table.*;
import client.IClient;

import javafx.scene.Scene;
import javafx.scene.control.*;
import action.*;
import db.interfaces.IEntity;
import javafx.scene.image.ImageView;
import java.util.Set;
import javafx.scene.text.Text;

@AutoGenerated
public class CustomerRatingScreen extends SceneBase {

	public CustomerRatingScreen(ISceneSwitcher sceneSwitcher, IClient client) throws Exception {
		super(sceneSwitcher, client);
		initialize();
	}

	public void initialize() throws Exception {
		Parent root = FXMLLoader.load(Main.class.getResource("CustomerRatingScreen.fxml"));
		_scene = new Scene(root);

		//scene switchers
		MfImageView mainMenuMarketingScreenControl = new MfImageView((ImageView) _scene.lookup("#scene$MainMenuMarketingScreen"));
		mainMenuMarketingScreenControl.addEvent((event) -> { _switcher.switchScene("MainMenuMarketingScreen"); });

		//entities instantiation
		CustomersRatings customersRatings = new CustomersRatings();
		AnalyticalRatings analyticalRatings = new AnalyticalRatings();

		//tables instantiation
		BorderPane customersRatingsBp = (BorderPane) _scene.lookup("#uitable$noneditable$single$customers_ratings");
		Table<CustomersRatings> customersRatingsTableWrapper = new Table<CustomersRatings>();
		MfTable<CustomersRatings> customersRatingsTable = new MfTable<CustomersRatings>(CustomersRatings.class);
		customersRatingsTable.setEditable(false);
		MfSingleDecorator<CustomersRatings> customersRatingsSingleDecorator = new MfSingleDecorator<CustomersRatings>();
		customersRatingsTableWrapper.addDecorator(customersRatingsSingleDecorator);
		customersRatingsTableWrapper.setTable(customersRatingsTable);
		customersRatingsBp.setCenter(customersRatingsTable);

		//initializations
		MfImageView filterAnalyticalRatingsControl = new MfImageView((ImageView) _scene.lookup("#action$collect$analytical_ratings"));
		ActionControl analyticalRatingsfilterAction = new ActionControl();
		analyticalRatingsfilterAction.setControl(filterAnalyticalRatingsControl);
		FilterCapability analyticalRatingsFilterCapability = new FilterCapability();
		analyticalRatingsFilterCapability.setQueryEntities(prepareQuery(analyticalRatings));
		analyticalRatingsfilterAction.addCapability(analyticalRatingsFilterCapability);
		analyticalRatingsfilterAction.setClient(_client);
		analyticalRatingsfilterAction.setCallback((response) -> {
			Collection<IEntity> entities = response.getEntities();
			for (IEntity ientity : entities) {
				AnalyticalRatings entity = (AnalyticalRatings) ientity;
			}
		});


	}
	private Map<IEntity, Map<String, String>> prepareQuery(AnalyticalRatings analyticalRatings) {
		Map<IEntity, Map<String, String>> map = new HashMap<IEntity, Map<String, String>>();
		
		Map<String, String> queryMap = new HashMap<String, String>();
		
		map.put(analyticalRatings, queryMap);
		return map;
	}
}
