package wrapper;

import annotations.AutoGenerated;
import application.Main;
import client.IClient;
import controls.MfText;
import db.entity.Car;
import db.entity.Customer;
import db.entity.FuelEnum;
import db.entity.FuelingPurchase;
import db.entity.Person;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.text.Text;
import sceneswitch.Context;
import sceneswitch.SceneBase;

@AutoGenerated
public class FastFuelingScreen extends SceneBase {

	private FuelingPurchase _fuelingPurchase;
	private Customer _customer;
	private Person _person;
	private Car _car;
	private FuelEnum _fuelEnum;

	private MfText _firstNameControl;
	private MfText _plateNumberControl;
	private MfText _pricePerLiterControl;
	private MfText _amountControl;
	private MfText _totalPriceControl;
	private MfText _fuelTypeKeyControl;

	public FastFuelingScreen(ISceneSwitcher sceneSwitcher, IClient client, Context context) throws Exception {
		super(sceneSwitcher, client, context);
		initialize();
	}

	public void initialize() throws Exception {
		Parent root = FXMLLoader.load(Main.class.getResource("FastFuelingScreen.fxml"));
		_scene = new Scene(root);

		//entities instantiation
		_fuelingPurchase = new FuelingPurchase();
		_customer = new Customer();
		_person = new Person();
		_car = new Car();
		_fuelEnum = new FuelEnum();

		//entities assignments
		_fuelingPurchase.setCustomer(_customer);
		_customer.setPerson(_person);
		_fuelingPurchase.setCar(_car);
		_fuelingPurchase.setFuelEnum(_fuelEnum);

		//controls instantiation
		_firstNameControl = new MfText((Text) _scene.lookup("#table$fueling_purchase$customer$person$first_name"));
		_plateNumberControl = new MfText((Text) _scene.lookup("#table$fueling_purchase$car$plate_number"));
		_pricePerLiterControl = new MfText((Text) _scene.lookup("#table$fueling_purchase$price_per_liter"));
		_amountControl = new MfText((Text) _scene.lookup("#table$fueling_purchase$amount"));
		_totalPriceControl = new MfText((Text) _scene.lookup("#table$fueling_purchase$total_price"));
		_fuelTypeKeyControl = new MfText((Text) _scene.lookup("#table$fueling_purchase$fuel_enum$fuel_type_key"));

		//fields initializations
		_firstNameControl.setField(_person.getClass().getDeclaredField("_first_name"));
		_firstNameControl.setEntity(_person);

		_plateNumberControl.setField(_car.getClass().getDeclaredField("_plate_number"));
		_plateNumberControl.setEntity(_car);

		_pricePerLiterControl.setField(_fuelingPurchase.getClass().getDeclaredField("_price_per_liter"));
		_pricePerLiterControl.setEntity(_fuelingPurchase);

		_amountControl.setField(_fuelingPurchase.getClass().getDeclaredField("_amount"));
		_amountControl.setEntity(_fuelingPurchase);

		_totalPriceControl.setField(_fuelingPurchase.getClass().getDeclaredField("_total_price"));
		_totalPriceControl.setEntity(_fuelingPurchase);

		_fuelTypeKeyControl.setField(_fuelEnum.getClass().getDeclaredField("_fuel_type_key"));
		_fuelTypeKeyControl.setEntity(_fuelEnum);


	}


	public FuelingPurchase getFuelingPurchase() {
		 return _fuelingPurchase;
	}

	public void setFuelingPurchase(FuelingPurchase fuelingPurchase) {
		 _fuelingPurchase = fuelingPurchase;
	}

	public Customer getCustomer() {
		 return _customer;
	}

	public void setCustomer(Customer customer) {
		 _customer = customer;
	}

	public Person getPerson() {
		 return _person;
	}

	public void setPerson(Person person) {
		 _person = person;
	}

	public Car getCar() {
		 return _car;
	}

	public void setCar(Car car) {
		 _car = car;
	}

	public FuelEnum getFuelEnum() {
		 return _fuelEnum;
	}

	public void setFuelEnum(FuelEnum fuelEnum) {
		 _fuelEnum = fuelEnum;
	}
}
