package wrapper;

import javafx.scene.layout.BorderPane;
import javafx.fxml.FXMLLoader;
import db.entity.*;
import adapter.base.ControlAdapter;
import java.util.HashSet;
import widgets.table.Table;
import application.Main;
import controls.*;
import annotations.AutoGenerated;
import java.util.HashMap;
import javafx.scene.Parent;
import sceneswitch.SceneBase;
import java.util.Map;
import java.util.Collection;
import table.MfTable;
import widgets.table.*;
import client.IClient;

import javafx.scene.Scene;
import javafx.scene.control.*;
import action.*;
import db.interfaces.IEntity;
import javafx.scene.image.ImageView;
import java.util.Set;
import javafx.scene.text.Text;

@AutoGenerated
public class FastFuelingScreen extends SceneBase {

	public FastFuelingScreen(ISceneSwitcher sceneSwitcher, IClient client) throws Exception {
		super(sceneSwitcher, client);
		initialize();
	}

	public void initialize() throws Exception {
		Parent root = FXMLLoader.load(Main.class.getResource("FastFuelingScreen.fxml"));
		_scene = new Scene(root);

		//entities instantiation
		FuelingPurchase fuelingPurchase = new FuelingPurchase();
		Customer customer = new Customer();
		Person person = new Person();
		Car car = new Car();
		FuelEnum fuelEnum = new FuelEnum();

		//entities assignments
		fuelingPurchase.setCustomer(customer);
		customer.setPerson(person);
		fuelingPurchase.setCar(car);
		fuelingPurchase.setFuelEnum(fuelEnum);

		//controls instantiation
		MfText firstNameControl = new MfText((Text) _scene.lookup("#table$fueling_purchase$customer$person$first_name"));
		MfText plateNumberControl = new MfText((Text) _scene.lookup("#table$fueling_purchase$car$plate_number"));
		MfText pricePerLiterControl = new MfText((Text) _scene.lookup("#table$fueling_purchase$price_per_liter"));
		MfText amountControl = new MfText((Text) _scene.lookup("#table$fueling_purchase$amount"));
		MfText totalPriceControl = new MfText((Text) _scene.lookup("#table$fueling_purchase$total_price"));
		MfText fuelTypeKeyControl = new MfText((Text) _scene.lookup("#table$fueling_purchase$fuel_enum$fuel_type_key"));

		//fields initializations
		firstNameControl.setField(person.getClass().getDeclaredField("_first_name"));
		firstNameControl.setEntity(person);

		plateNumberControl.setField(car.getClass().getDeclaredField("_plate_number"));
		plateNumberControl.setEntity(car);

		pricePerLiterControl.setField(fuelingPurchase.getClass().getDeclaredField("_price_per_liter"));
		pricePerLiterControl.setEntity(fuelingPurchase);

		amountControl.setField(fuelingPurchase.getClass().getDeclaredField("_amount"));
		amountControl.setEntity(fuelingPurchase);

		totalPriceControl.setField(fuelingPurchase.getClass().getDeclaredField("_total_price"));
		totalPriceControl.setEntity(fuelingPurchase);

		fuelTypeKeyControl.setField(fuelEnum.getClass().getDeclaredField("_fuel_type_key"));
		fuelTypeKeyControl.setEntity(fuelEnum);


	}
	private Map<IEntity, Map<String, String>> prepareQuery(StationManagerReports stationManagerReports) {
		Map<IEntity, Map<String, String>> map = new HashMap<IEntity, Map<String, String>>();
		
		Map<String, String> queryMap = new HashMap<String, String>();
		
		map.put(stationManagerReports, queryMap);
		return map;
	}
}
