package wrapper;

import java.util.HashSet;
import java.util.Set;

import action.ActionControl;
import action.UpdateCapability;
import adapter.base.ControlAdapter;
import annotations.AutoGenerated;
import application.Main;
import client.IClient;
import controls.MfImageView;
import controls.MfText;
import controls.MfTextField;
import db.entity.FuelEnum;
import db.entity.Station;
import db.entity.StationsFuel;
import db.interfaces.IEntity;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.TextField;
import javafx.scene.image.ImageView;
import javafx.scene.text.Text;
import sceneswitch.Context;
import sceneswitch.SceneBase;

@AutoGenerated
public class FuelThresholdLevelScreen extends SceneBase {

	private Station _station;
	private StationsFuel _stationsFuelMotorcyclesFuelLowLevel;
	private FuelEnum _fuelEnum;
	private StationsFuel _stationsFuelSolerFuelLowLevel;
	private StationsFuel _stationsFuelBenzinFuelLowLevel;
	private StationsFuel _stationsFuel;

	private MfTextField _fuelLowLevelControlMotorcyclesFuelLowLevel;
	private MfTextField _fuelLowLevelControlSolerFuelLowLevel;
	private MfTextField _fuelLowLevelControlBenzinFuelLowLevel;
	private MfImageView _updateStationsFuelControl;
	private ActionControl _stationsFuelupdateAction;
	private MfImageView _mainMenuStationManagerScreenControl;
	private MfText _fuelLowLevelControlTxt;
	private MfText _currentAmountControlTxt;

	public FuelThresholdLevelScreen(ISceneSwitcher sceneSwitcher, IClient client, Context context) throws Exception {
		super(sceneSwitcher, client, context);
		initialize();
	}

	public void initialize() throws Exception {
		Parent root = FXMLLoader.load(Main.class.getResource("FuelThresholdLevelScreen.fxml"));
		_scene = new Scene(root);

		//scene switchers
		_mainMenuStationManagerScreenControl = new MfImageView((ImageView) _scene.lookup("#scene$MainMenuStationManagerScreen"));
		_mainMenuStationManagerScreenControl.addEvent((event) -> { _switcher.switchScene("MainMenuStationManagerScreen"); });

		//entities instantiation
		_station = new Station();
		_stationsFuelMotorcyclesFuelLowLevel = new StationsFuel();
		_fuelEnum = new FuelEnum();
		_stationsFuelSolerFuelLowLevel = new StationsFuel();
		_stationsFuelBenzinFuelLowLevel = new StationsFuel();
		_stationsFuel = new StationsFuel();

		//entities assignments
		_stationsFuelMotorcyclesFuelLowLevel.setStation(_station);
		_stationsFuelMotorcyclesFuelLowLevel.setFuelEnum(_fuelEnum);
		_stationsFuelSolerFuelLowLevel.setStation(_station);
		_stationsFuelSolerFuelLowLevel.setFuelEnum(_fuelEnum);
		_stationsFuelBenzinFuelLowLevel.setStation(_station);
		_stationsFuelBenzinFuelLowLevel.setFuelEnum(_fuelEnum);

		//controls instantiation
		_fuelLowLevelControlMotorcyclesFuelLowLevel = new MfTextField((TextField) _scene.lookup("#table$station$stations_fuel$fuel_enum$$$motorcycles$fuel_low_level"));
		_fuelLowLevelControlSolerFuelLowLevel = new MfTextField((TextField) _scene.lookup("#table$station$stations_fuel$fuel_enum$$$soler$fuel_low_level"));
		_fuelLowLevelControlBenzinFuelLowLevel = new MfTextField((TextField) _scene.lookup("#table$station$stations_fuel$fuel_enum$$$benzin$fuel_low_level"));
		_fuelLowLevelControlTxt = new MfText((Text) _scene.lookup("#table$stations_fuel$fuel_low_level$$$txt"));
		_currentAmountControlTxt = new MfText((Text) _scene.lookup("#table$stations_fuel$current_amount$$$txt"));

		//initializations
		_updateStationsFuelControl = new MfImageView((ImageView) _scene.lookup("#action$update$station$stations_fuel"));
		_stationsFuelupdateAction = new ActionControl();
		_stationsFuelupdateAction.setControl(_updateStationsFuelControl);
		UpdateCapability stationsFuelUpdateCapability = new UpdateCapability();
		Set<IEntity> stationsFuelUpdateEntities = new HashSet<IEntity>();
		stationsFuelUpdateCapability.setEntities(stationsFuelUpdateEntities);
		_stationsFuelupdateAction.addCapability(stationsFuelUpdateCapability);
		_stationsFuelupdateAction.setClient(_client);
		_stationsFuelupdateAction.setCallback((response) -> {
			
		});

		//fields initializations
		_fuelLowLevelControlMotorcyclesFuelLowLevel.setField(_stationsFuelMotorcyclesFuelLowLevel.getClass().getDeclaredField("_fuel_low_level"));
		_fuelLowLevelControlMotorcyclesFuelLowLevel.setEntity(_stationsFuelMotorcyclesFuelLowLevel);

		_fuelLowLevelControlSolerFuelLowLevel.setField(_stationsFuelSolerFuelLowLevel.getClass().getDeclaredField("_fuel_low_level"));
		_fuelLowLevelControlSolerFuelLowLevel.setEntity(_stationsFuelSolerFuelLowLevel);

		_fuelLowLevelControlBenzinFuelLowLevel.setField(_stationsFuelBenzinFuelLowLevel.getClass().getDeclaredField("_fuel_low_level"));
		_fuelLowLevelControlBenzinFuelLowLevel.setEntity(_stationsFuelBenzinFuelLowLevel);

		_fuelLowLevelControlTxt.setField(_stationsFuel.getClass().getDeclaredField("_fuel_low_level"));
		_fuelLowLevelControlTxt.setEntity(_stationsFuel);

		_currentAmountControlTxt.setField(_stationsFuel.getClass().getDeclaredField("_current_amount"));
		_currentAmountControlTxt.setEntity(_stationsFuel);

		_fuelLowLevelControlTxt.setField(_stationsFuel.getClass().getDeclaredField("_fuel_low_level"));
		_fuelLowLevelControlTxt.setEntity(_stationsFuel);

		_currentAmountControlTxt.setField(_stationsFuel.getClass().getDeclaredField("_current_amount"));
		_currentAmountControlTxt.setEntity(_stationsFuel);

		_fuelLowLevelControlTxt.setField(_stationsFuel.getClass().getDeclaredField("_fuel_low_level"));
		_fuelLowLevelControlTxt.setEntity(_stationsFuel);

		_currentAmountControlTxt.setField(_stationsFuel.getClass().getDeclaredField("_current_amount"));
		_currentAmountControlTxt.setEntity(_stationsFuel);

		//grouping
		groupControls(new ControlAdapter[] { _fuelLowLevelControlMotorcyclesFuelLowLevel, _fuelLowLevelControlSolerFuelLowLevel, _fuelLowLevelControlBenzinFuelLowLevel });
		groupControls(new ControlAdapter[] { _fuelLowLevelControlTxt, _fuelLowLevelControlTxt, _fuelLowLevelControlTxt });
		groupControls(new ControlAdapter[] { _currentAmountControlTxt, _currentAmountControlTxt, _currentAmountControlTxt });

	}


	public Station getStation() {
		 return _station;
	}

	public void setStation(Station station) {
		 _station = station;
	}

	public StationsFuel getStationsFuelMotorcyclesFuelLowLevel() {
		 return _stationsFuelMotorcyclesFuelLowLevel;
	}

	public void setStationsFuelMotorcyclesFuelLowLevel(StationsFuel stationsFuelMotorcyclesFuelLowLevel) {
		 _stationsFuelMotorcyclesFuelLowLevel = stationsFuelMotorcyclesFuelLowLevel;
	}

	public FuelEnum getFuelEnum() {
		 return _fuelEnum;
	}

	public void setFuelEnum(FuelEnum fuelEnum) {
		 _fuelEnum = fuelEnum;
	}

	public StationsFuel getStationsFuelSolerFuelLowLevel() {
		 return _stationsFuelSolerFuelLowLevel;
	}

	public void setStationsFuelSolerFuelLowLevel(StationsFuel stationsFuelSolerFuelLowLevel) {
		 _stationsFuelSolerFuelLowLevel = stationsFuelSolerFuelLowLevel;
	}

	public StationsFuel getStationsFuelBenzinFuelLowLevel() {
		 return _stationsFuelBenzinFuelLowLevel;
	}

	public void setStationsFuelBenzinFuelLowLevel(StationsFuel stationsFuelBenzinFuelLowLevel) {
		 _stationsFuelBenzinFuelLowLevel = stationsFuelBenzinFuelLowLevel;
	}

	public StationsFuel getStationsFuel() {
		 return _stationsFuel;
	}

	public void setStationsFuel(StationsFuel stationsFuel) {
		 _stationsFuel = stationsFuel;
	}
}
