package wrapper;

import javafx.scene.layout.BorderPane;
import javafx.fxml.FXMLLoader;
import db.entity.*;
import adapter.base.ControlAdapter;
import java.util.HashSet;
import widgets.table.Table;
import application.Main;
import controls.*;
import annotations.AutoGenerated;
import java.util.HashMap;
import javafx.scene.Parent;
import sceneswitch.SceneBase;
import java.util.Map;
import java.util.Collection;
import table.MfTable;
import widgets.table.*;
import client.IClient;

import javafx.scene.Scene;
import javafx.scene.control.*;
import action.*;
import db.interfaces.IEntity;
import javafx.scene.image.ImageView;
import java.util.Set;
import javafx.scene.text.Text;

@AutoGenerated
public class HomeHeatingOrderDetailsScreen extends SceneBase {

	public HomeHeatingOrderDetailsScreen(ISceneSwitcher sceneSwitcher, IClient client) throws Exception {
		super(sceneSwitcher, client);
		initialize();
	}

	public void initialize() throws Exception {
		Parent root = FXMLLoader.load(Main.class.getResource("HomeHeatingOrderDetailsScreen.fxml"));
		_scene = new Scene(root);

		//scene switchers
		MfImageView homeHeatingNewOrderScreenControl = new MfImageView((ImageView) _scene.lookup("#scene$HomeHeatingNewOrderScreen"));
		homeHeatingNewOrderScreenControl.addEvent((event) -> { _switcher.switchScene("HomeHeatingNewOrderScreen"); });

		//entities instantiation
		HomeHeatingOrder homeHeatingOrder = new HomeHeatingOrder();
		Customer customer = new Customer();
		Payment payment = new Payment();
		Person person = new Person();
		Address address = new Address();

		//entities assignments
		homeHeatingOrder.setCustomer(customer);
		customer.setPayment(payment);
		customer.setPerson(person);
		customer.setAddress(address);

		//controls instantiation
		MfText creditCardNumberControl = new MfText((Text) _scene.lookup("#table$home_heating_order$customer$payment$credit_card_number"));
		MfText firstNameControl = new MfText((Text) _scene.lookup("#table$home_heating_order$customer$person$first_name"));
		MfText lastNameControl = new MfText((Text) _scene.lookup("#table$home_heating_order$customer$person$last_name"));
		MfText cityControl = new MfText((Text) _scene.lookup("#table$home_heating_order$customer$address$city"));
		MfText streetControl = new MfText((Text) _scene.lookup("#table$home_heating_order$customer$address$street"));
		MfText apartmentControl = new MfText((Text) _scene.lookup("#table$home_heating_order$customer$address$apartment"));

		//initializations
		MfImageView insertHomeHeatingOrderControl = new MfImageView((ImageView) _scene.lookup("#action$insert$home_heating_order"));
		ActionControl homeHeatingOrderinsertAction = new ActionControl();
		homeHeatingOrderinsertAction.setControl(insertHomeHeatingOrderControl);
		InsertCapability homeHeatingOrderInsertCapability = new InsertCapability();
		homeHeatingOrderInsertCapability.addEntity(homeHeatingOrder);
		homeHeatingOrderinsertAction.addCapability(homeHeatingOrderInsertCapability);
		homeHeatingOrderinsertAction.setClient(_client);
		homeHeatingOrderinsertAction.setCallback((response) -> {
			
		});

		//fields initializations
		creditCardNumberControl.setField(payment.getClass().getDeclaredField("_credit_card_number"));
		creditCardNumberControl.setEntity(payment);

		firstNameControl.setField(person.getClass().getDeclaredField("_first_name"));
		firstNameControl.setEntity(person);

		lastNameControl.setField(person.getClass().getDeclaredField("_last_name"));
		lastNameControl.setEntity(person);

		cityControl.setField(address.getClass().getDeclaredField("_city"));
		cityControl.setEntity(address);

		streetControl.setField(address.getClass().getDeclaredField("_street"));
		streetControl.setEntity(address);

		apartmentControl.setField(address.getClass().getDeclaredField("_apartment"));
		apartmentControl.setEntity(address);


	}
	private Map<IEntity, Map<String, String>> prepareQuery(StationManagerReports stationManagerReports) {
		Map<IEntity, Map<String, String>> map = new HashMap<IEntity, Map<String, String>>();
		
		Map<String, String> queryMap = new HashMap<String, String>();
		
		map.put(stationManagerReports, queryMap);
		return map;
	}
}
