package wrapper;

import javafx.scene.layout.BorderPane;
import javafx.fxml.FXMLLoader;
import adapter.base.ControlAdapter;
import java.util.HashSet;
import widgets.table.Table;
import controls.*;
import annotations.AutoGenerated;
import java.util.HashMap;
import javafx.scene.Parent;
import sceneswitch.SceneBase;
import table.MfTable;
import widgets.table.*;
import javafx.scene.Scene;
import javafx.scene.control.*;
import action.*;
import db.interfaces.IEntity;
import javafx.scene.image.ImageView;
import java.util.Set;
import javafx.scene.text.Text;

@AutoGenerated
public class HomeHeatingNewOrderScreen extends SceneBase {

	public HomeHeatingNewOrderScreen(ISceneSwitcher sceneSwitcher) {
		super(sceneSwitcher);
	}

	public void initialize() {
		Parent root = FXMLLoader.load(getClass().getResource("HomeHeatingNewOrderScreen.fxml"));
		_scene = new Scene(root);

		//entities instantiation
		HomeHeatingOrder homeHeatingOrder = new HomeHeatingOrder();

		//controls instantiation
		MfTextField amountControl = new MfTextField((TextField) _scene.lookup("#table$home_heating_order$amount"));
		MfCheckBox orderUrgencyControlRegular = new MfCheckBox((CheckBox) _scene.lookup("#table$home_heating_order$order_urgency$$regular"));
		MfCheckBox orderUrgencyControlExpress = new MfCheckBox((CheckBox) _scene.lookup("#table$home_heating_order$order_urgency$$express"));
		MfText pricePerLiterControl = new MfText((Text) _scene.lookup("#table$home_heating_order$price_per_liter"));
		MfText totalPriceControl = new MfText((Text) _scene.lookup("#table$home_heating_order$total_price"));

		//initializations
		MfHyperlink maimMenuCustomerScreenControl = new MfHyperlink((Hyperlink) _scene.lookup("#scene$MaimMenuCustomerScreen"));
		maimMenuCustomerScreenControl.addEvent((event) -> { _switcher.switchScene("MaimMenuCustomerScreen"); });
		MfImageView maimMenuCustomerScreenControl = new MfImageView((ImageView) _scene.lookup("#scene$MaimMenuCustomerScreen"));
		maimMenuCustomerScreenControl.addEvent((event) -> { _switcher.switchScene("MaimMenuCustomerScreen"); });
		MfImageView homeHeatingOrderDetailsScreenControl = new MfImageView((ImageView) _scene.lookup("#scene$HomeHeatingOrderDetailsScreen"));
		homeHeatingOrderDetailsScreenControl.addEvent((event) -> { _switcher.switchScene("HomeHeatingOrderDetailsScreen"); });

		//fields initializations
		amountControl.setField(homeHeatingOrder.getClass().getField("_amount"));
		amountControl.setEntity(homeHeatingOrder);

		orderUrgencyControlRegular.setField(homeHeatingOrder.getClass().getField("_order_urgency"));
		orderUrgencyControlRegular.setEntity(homeHeatingOrder);

		orderUrgencyControlExpress.setField(homeHeatingOrder.getClass().getField("_order_urgency"));
		orderUrgencyControlExpress.setEntity(homeHeatingOrder);

		pricePerLiterControl.setField(homeHeatingOrder.getClass().getField("_price_per_liter"));
		pricePerLiterControl.setEntity(homeHeatingOrder);

		totalPriceControl.setField(homeHeatingOrder.getClass().getField("_total_price"));
		totalPriceControl.setEntity(homeHeatingOrder);

		//grouping
		groupControls(new ControlAdapter[] { orderUrgencyControlRegular, orderUrgencyControlExpress });
	}

}
