package wrapper;

import java.util.ArrayList;
import java.util.Collection;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import action.ActionControl;
import action.FilterCapability;
import adapter.base.ControlAdapter;
import annotations.AutoGenerated;
import application.Main;
import client.IClient;
import controls.MfComboBox;
import controls.MfImageView;
import controls.MfText;
import db.entity.FuelEnum;
import db.entity.FuelingPurchase;
import db.entity.Station;
import db.entity.StationManagerReports;
import db.interfaces.IEntity;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.ComboBox;
import javafx.scene.image.ImageView;
import javafx.scene.text.Text;
import messages.QueryContainer;
import sceneswitch.Context;
import sceneswitch.SceneBase;

@AutoGenerated
public class IncomeReportScreen extends SceneBase {

	private StationManagerReports _stationManagerReports;
	private Station _station;
	private FuelingPurchase _fuelingPurchaseBenzinAmount;
	private FuelEnum _fuelEnum;
	private FuelingPurchase _fuelingPurchaseSolerAmount;
	private FuelingPurchase _fuelingPurchaseMotorcycleAmount;
	private FuelingPurchase _fuelingPurchaseBenzinTotalPrice;
	private FuelingPurchase _fuelingPurchaseSolerTotalPrice;
	private FuelingPurchase _fuelingPurchaseMotorcycleTotalPrice;

	private MfImageView _mainMenuStationManagerScreenControl;
	private MfText _reportDateControlTxt;
	private MfText _stationNameControl;
	private MfText _amountControlBenzinAmount;
	private MfText _amountControlSolerAmount;
	private MfText _amountControlMotorcycleAmount;
	private MfText _totalPriceControlBenzinTotalPrice;
	private MfText _totalPriceControlSolerTotalPrice;
	private MfText _totalPriceControlMotorcycleTotalPrice;
	private MfImageView _filterStationManagerReportsControl;
	private ActionControl _stationManagerReportsfilterAction;
	private MfComboBox _reportDateControlCmb;

	public IncomeReportScreen(ISceneSwitcher sceneSwitcher, IClient client, Context context) throws Exception {
		super(sceneSwitcher, client, context);
		initialize();
	}

	public void initialize() throws Exception {
		Parent root = FXMLLoader.load(Main.class.getResource("IncomeReportScreen.fxml"));
		_scene = new Scene(root);

		//scene switchers
		_mainMenuStationManagerScreenControl = new MfImageView((ImageView) _scene.lookup("#scene$MainMenuStationManagerScreen"));
		_mainMenuStationManagerScreenControl.addEvent((event) -> { _switcher.switchScene("MainMenuStationManagerScreen"); });

		//entities instantiation
		_stationManagerReports = new StationManagerReports();
		_station = new Station();
		_fuelingPurchaseBenzinAmount = new FuelingPurchase();
		_fuelEnum = new FuelEnum();
		_fuelingPurchaseSolerAmount = new FuelingPurchase();
		_fuelingPurchaseMotorcycleAmount = new FuelingPurchase();
		_fuelingPurchaseBenzinTotalPrice = new FuelingPurchase();
		_fuelingPurchaseSolerTotalPrice = new FuelingPurchase();
		_fuelingPurchaseMotorcycleTotalPrice = new FuelingPurchase();

		//entities assignments
		_stationManagerReports.setStation(_station);
		_fuelingPurchaseBenzinAmount.setStation(_station);
		_fuelingPurchaseBenzinAmount.setFuelEnum(_fuelEnum);
		_stationManagerReports.setFuelEnum(_fuelEnum);
		_fuelingPurchaseSolerAmount.setStation(_station);
		_fuelingPurchaseSolerAmount.setFuelEnum(_fuelEnum);
		_fuelingPurchaseMotorcycleAmount.setStation(_station);
		_fuelingPurchaseMotorcycleAmount.setFuelEnum(_fuelEnum);
		_fuelingPurchaseBenzinTotalPrice.setStation(_station);
		_fuelingPurchaseBenzinTotalPrice.setFuelEnum(_fuelEnum);
		_fuelingPurchaseSolerTotalPrice.setStation(_station);
		_fuelingPurchaseSolerTotalPrice.setFuelEnum(_fuelEnum);
		_fuelingPurchaseMotorcycleTotalPrice.setStation(_station);
		_fuelingPurchaseMotorcycleTotalPrice.setFuelEnum(_fuelEnum);

		//controls instantiation
		_reportDateControlTxt = new MfText((Text) _scene.lookup("#table$station_manager_reports$report_date$$$txt"));
		_stationNameControl = new MfText((Text) _scene.lookup("#table$station_manager_reports$station$station_name"));
		_amountControlBenzinAmount = new MfText((Text) _scene.lookup("#table$station_manager_reports$station$fueling_purchase$fuel_enum$$$benzin$amount"));
		_amountControlSolerAmount = new MfText((Text) _scene.lookup("#table$station_manager_reports$station$fueling_purchase$fuel_enum$$$soler$amount"));
		_amountControlMotorcycleAmount = new MfText((Text) _scene.lookup("#table$station_manager_reports$station$fueling_purchase$fuel_enum$$$motorcycle$amount"));
		_totalPriceControlBenzinTotalPrice = new MfText((Text) _scene.lookup("#table$station_manager_reports$station$fueling_purchase$fuel_enum$$$benzin$total_price"));
		_totalPriceControlSolerTotalPrice = new MfText((Text) _scene.lookup("#table$station_manager_reports$station$fueling_purchase$fuel_enum$$$soler$total_price"));
		_totalPriceControlMotorcycleTotalPrice = new MfText((Text) _scene.lookup("#table$station_manager_reports$station$fueling_purchase$fuel_enum$$$motorcycle$total_price"));
		_reportDateControlCmb = new MfComboBox((ComboBox) _scene.lookup("#table$station_manager_reports$report_date$$$cmb"));

		//initializations
		_filterStationManagerReportsControl = new MfImageView((ImageView) _scene.lookup("#action$collect$station_manager_reports"));
		_stationManagerReportsfilterAction = new ActionControl();
		_stationManagerReportsfilterAction.setControl(_filterStationManagerReportsControl);
		FilterCapability stationManagerReportsFilterCapability = new FilterCapability();
		stationManagerReportsFilterCapability.setQueryContainers(prepareQuery(_stationManagerReports));
		_stationManagerReportsfilterAction.addCapability(stationManagerReportsFilterCapability);
		_stationManagerReportsfilterAction.setClient(_client);
		_stationManagerReportsfilterAction.setCallback((response) -> {
			Collection<IEntity> entities = response.getEntities();
			for (IEntity ientity : entities) {
				StationManagerReports entity = (StationManagerReports) ientity;
			}
		});

		//fields initializations
		_reportDateControlTxt.setField(_stationManagerReports.getClass().getDeclaredField("_report_date"));
		_reportDateControlTxt.setEntity(_stationManagerReports);

		_stationNameControl.setField(_station.getClass().getDeclaredField("_station_name"));
		_stationNameControl.setEntity(_station);

		_amountControlBenzinAmount.setField(_fuelingPurchaseBenzinAmount.getClass().getDeclaredField("_amount"));
		_amountControlBenzinAmount.setEntity(_fuelingPurchaseBenzinAmount);

		_amountControlSolerAmount.setField(_fuelingPurchaseSolerAmount.getClass().getDeclaredField("_amount"));
		_amountControlSolerAmount.setEntity(_fuelingPurchaseSolerAmount);

		_amountControlMotorcycleAmount.setField(_fuelingPurchaseMotorcycleAmount.getClass().getDeclaredField("_amount"));
		_amountControlMotorcycleAmount.setEntity(_fuelingPurchaseMotorcycleAmount);

		_totalPriceControlBenzinTotalPrice.setField(_fuelingPurchaseBenzinTotalPrice.getClass().getDeclaredField("_total_price"));
		_totalPriceControlBenzinTotalPrice.setEntity(_fuelingPurchaseBenzinTotalPrice);

		_totalPriceControlSolerTotalPrice.setField(_fuelingPurchaseSolerTotalPrice.getClass().getDeclaredField("_total_price"));
		_totalPriceControlSolerTotalPrice.setEntity(_fuelingPurchaseSolerTotalPrice);

		_totalPriceControlMotorcycleTotalPrice.setField(_fuelingPurchaseMotorcycleTotalPrice.getClass().getDeclaredField("_total_price"));
		_totalPriceControlMotorcycleTotalPrice.setEntity(_fuelingPurchaseMotorcycleTotalPrice);

		_reportDateControlCmb.setField(_stationManagerReports.getClass().getDeclaredField("_report_date"));
		_reportDateControlCmb.setEntity(_stationManagerReports);

		//grouping
		groupControls(new ControlAdapter[] { _reportDateControlTxt, _reportDateControlCmb });
		groupControls(new ControlAdapter[] { _amountControlBenzinAmount, _amountControlSolerAmount, _amountControlMotorcycleAmount });
		groupControls(new ControlAdapter[] { _totalPriceControlBenzinTotalPrice, _totalPriceControlSolerTotalPrice, _totalPriceControlMotorcycleTotalPrice });

	}

	private List<QueryContainer> prepareQuery(StationManagerReports stationManagerReports) {
		List<QueryContainer> containers = new ArrayList<QueryContainer>();
		
		Map<String, String> queryMap = new HashMap<String, String>();
		
		QueryContainer container = new QueryContainer();
		container.setQueryEntity(stationManagerReports);
		container.setQueryMap(queryMap);
		containers.add(container);
		return containers;
	}

	public StationManagerReports getStationManagerReports() {
		 return _stationManagerReports;
	}

	public void setStationManagerReports(StationManagerReports stationManagerReports) {
		 _stationManagerReports = stationManagerReports;
	}

	public Station getStation() {
		 return _station;
	}

	public void setStation(Station station) {
		 _station = station;
	}

	public FuelingPurchase getFuelingPurchaseBenzinAmount() {
		 return _fuelingPurchaseBenzinAmount;
	}

	public void setFuelingPurchaseBenzinAmount(FuelingPurchase fuelingPurchaseBenzinAmount) {
		 _fuelingPurchaseBenzinAmount = fuelingPurchaseBenzinAmount;
	}

	public FuelEnum getFuelEnum() {
		 return _fuelEnum;
	}

	public void setFuelEnum(FuelEnum fuelEnum) {
		 _fuelEnum = fuelEnum;
	}

	public FuelingPurchase getFuelingPurchaseSolerAmount() {
		 return _fuelingPurchaseSolerAmount;
	}

	public void setFuelingPurchaseSolerAmount(FuelingPurchase fuelingPurchaseSolerAmount) {
		 _fuelingPurchaseSolerAmount = fuelingPurchaseSolerAmount;
	}

	public FuelingPurchase getFuelingPurchaseMotorcycleAmount() {
		 return _fuelingPurchaseMotorcycleAmount;
	}

	public void setFuelingPurchaseMotorcycleAmount(FuelingPurchase fuelingPurchaseMotorcycleAmount) {
		 _fuelingPurchaseMotorcycleAmount = fuelingPurchaseMotorcycleAmount;
	}

	public FuelingPurchase getFuelingPurchaseBenzinTotalPrice() {
		 return _fuelingPurchaseBenzinTotalPrice;
	}

	public void setFuelingPurchaseBenzinTotalPrice(FuelingPurchase fuelingPurchaseBenzinTotalPrice) {
		 _fuelingPurchaseBenzinTotalPrice = fuelingPurchaseBenzinTotalPrice;
	}

	public FuelingPurchase getFuelingPurchaseSolerTotalPrice() {
		 return _fuelingPurchaseSolerTotalPrice;
	}

	public void setFuelingPurchaseSolerTotalPrice(FuelingPurchase fuelingPurchaseSolerTotalPrice) {
		 _fuelingPurchaseSolerTotalPrice = fuelingPurchaseSolerTotalPrice;
	}

	public FuelingPurchase getFuelingPurchaseMotorcycleTotalPrice() {
		 return _fuelingPurchaseMotorcycleTotalPrice;
	}

	public void setFuelingPurchaseMotorcycleTotalPrice(FuelingPurchase fuelingPurchaseMotorcycleTotalPrice) {
		 _fuelingPurchaseMotorcycleTotalPrice = fuelingPurchaseMotorcycleTotalPrice;
	}
}
