package wrapper;

import java.util.ArrayList;
import java.util.Collection;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import action.ActionControl;
import action.FilterCapability;
import action.InsertCapability;
import adapter.base.ControlAdapter;
import annotations.AutoGenerated;
import application.Main;
import client.IClient;
import controls.MfComboBox;
import controls.MfHyperlink;
import controls.MfImageView;
import controls.MfText;
import db.entity.FuelEnum;
import db.entity.Station;
import db.entity.StationManagerReports;
import db.entity.StationsFuel;
import db.interfaces.IEntity;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.ComboBox;
import javafx.scene.control.Hyperlink;
import javafx.scene.image.ImageView;
import javafx.scene.text.Text;
import messages.QueryContainer;
import sceneswitch.Context;
import sceneswitch.ISceneSwitcher;
import sceneswitch.SceneBase;

@AutoGenerated
public class InventoryReportScreen extends SceneBase {

	private StationManagerReports _stationManagerReportsSolerAmount;
	private FuelEnum _fuelEnum;
	private StationManagerReports _stationManagerReportsMotorcyclesAmount;
	private StationManagerReports _stationManagerReports;
	private Station _station;
	private StationManagerReports _stationManagerReportsBenzinAmount;
	private StationsFuel _stationsFuel;

	private MfHyperlink _main_menu_managerControl;
	private MfImageView _mainMenuStationManagerScreenControl;
	private MfText _amountControlSolerAmount;
	private MfText _amountControlMotorcyclesAmount;
	private MfText _stationNameControl;
	private MfText _amountControlBenzinAmount;
	private MfImageView _filterStationsFuelControl;
	private ActionControl _stationsFuelfilterAction;
	private MfComboBox _reportYearControl;
	private MfComboBox _reportQuarterControl;
	private MfImageView _insertStationManagerReportsControl;
	private ActionControl _stationManagerReportsinsertAction;

	public InventoryReportScreen(ISceneSwitcher sceneSwitcher, IClient client, Context context) throws Exception {
		super(sceneSwitcher, client, context);
	}

	@Override
	public void initialize() throws Exception {
		Parent root = FXMLLoader.load(Main.class.getResource("InventoryReportScreen.fxml"));
		_scene = new Scene(root);

		//scene switchers
		_main_menu_managerControl = new MfHyperlink((Hyperlink) _scene.lookup("#scene$main_menu_manager"));
		_main_menu_managerControl.addEvent((event) -> { _switcher.switchScene("main_menu_manager"); });

		_mainMenuStationManagerScreenControl = new MfImageView((ImageView) _scene.lookup("#scene$MainMenuStationManagerScreen"));
		_mainMenuStationManagerScreenControl.addEvent((event) -> { _switcher.switchScene("MainMenuStationManagerScreen"); });

		//entities instantiation
		if (_stationManagerReportsSolerAmount == null) {
			_stationManagerReportsSolerAmount = new StationManagerReports();
		}
		if (_fuelEnum == null) {
			_fuelEnum = new FuelEnum();
		}
		if (_stationManagerReportsMotorcyclesAmount == null) {
			_stationManagerReportsMotorcyclesAmount = new StationManagerReports();
		}
		if (_stationManagerReports == null) {
			_stationManagerReports = new StationManagerReports();
		}
		if (_station == null) {
			_station = new Station();
		}
		if (_stationManagerReportsBenzinAmount == null) {
			_stationManagerReportsBenzinAmount = new StationManagerReports();
		}
		if (_stationsFuel == null) {
			_stationsFuel = new StationsFuel();
		}

		//entities assignments
		_stationManagerReportsSolerAmount.setFuelEnum(_fuelEnum);
		_stationManagerReportsMotorcyclesAmount.setFuelEnum(_fuelEnum);
		_stationManagerReports.setStation(_station);
		_stationManagerReportsBenzinAmount.setFuelEnum(_fuelEnum);

		//controls instantiation
		_amountControlSolerAmount = new MfText((Text) _scene.lookup("#table$station_manager_reports$fuel_enum$$$soler$amount"));
		_amountControlMotorcyclesAmount = new MfText((Text) _scene.lookup("#table$station_manager_reports$fuel_enum$$$motorcycles$amount"));
		_stationNameControl = new MfText((Text) _scene.lookup("#table$station_manager_reports$station$station_name"));
		_amountControlBenzinAmount = new MfText((Text) _scene.lookup("#table$station_manager_reports$fuel_enum$$$benzin$amount"));
		_reportYearControl = new MfComboBox((ComboBox) _scene.lookup("#table$station_manager_reports$report_year"));
		_reportQuarterControl = new MfComboBox((ComboBox) _scene.lookup("#table$station_manager_reports$report_quarter"));

		//initializations
		_filterStationsFuelControl = new MfImageView((ImageView) _scene.lookup("#action$collect$stations_fuel"));
		_filterStationsFuelControl.
			setMouseImages("@resource/images/Search_btn.png", "@resource/images/Search_overbtn.png", "@resource/images/Search_clickbtn.png");
		_stationsFuelfilterAction = new ActionControl();
		_stationsFuelfilterAction.setControl(_filterStationsFuelControl);
		FilterCapability stationsFuelFilterCapability = new FilterCapability();
		stationsFuelFilterCapability.setQueryContainers(prepareQuery(_stationsFuel));
		_stationsFuelfilterAction.addCapability(stationsFuelFilterCapability);
		_stationsFuelfilterAction.setClient(_client);
		_stationsFuelfilterAction.setPreSend((request) -> {

			return true;
		});
		_stationsFuelfilterAction.setCallback((response) -> {
			Collection<IEntity> entities = response.getEntities();
			for (IEntity ientity : entities) {
				StationsFuel entity = (StationsFuel) ientity;
			}
		});

		_insertStationManagerReportsControl = new MfImageView((ImageView) _scene.lookup("#action$insert$station_manager_reports"));
		_insertStationManagerReportsControl.
			setMouseImages("@resource/images/ProduceReport_btn.png", "@resource/images/ProduceReport_overbtn.png", "@resource/images/ProduceReport_clickbtn.png");
		_stationManagerReportsinsertAction = new ActionControl();
		_stationManagerReportsinsertAction.setControl(_insertStationManagerReportsControl);
		InsertCapability stationManagerReportsInsertCapability = new InsertCapability();
		stationManagerReportsInsertCapability.addEntity(_stationManagerReports);
		_stationManagerReportsinsertAction.addCapability(stationManagerReportsInsertCapability);
		_stationManagerReportsinsertAction.setClient(_client);
		_stationManagerReportsinsertAction.setPreSend((request) -> {

			return true;
		});
		_stationManagerReportsinsertAction.setCallback((response) -> {
			
		});

		//fields initializations
		_amountControlSolerAmount.setField(_stationManagerReportsSolerAmount.getClass().getDeclaredField("_amount"));
		_amountControlSolerAmount.setEntity(_stationManagerReportsSolerAmount);

		_amountControlMotorcyclesAmount.setField(_stationManagerReportsMotorcyclesAmount.getClass().getDeclaredField("_amount"));
		_amountControlMotorcyclesAmount.setEntity(_stationManagerReportsMotorcyclesAmount);

		_stationNameControl.setField(_station.getClass().getDeclaredField("_station_name"));
		_stationNameControl.setEntity(_station);

		_amountControlBenzinAmount.setField(_stationManagerReportsBenzinAmount.getClass().getDeclaredField("_amount"));
		_amountControlBenzinAmount.setEntity(_stationManagerReportsBenzinAmount);

		_reportYearControl.setField(_stationManagerReports.getClass().getDeclaredField("_report_year"));
		_reportYearControl.setEntity(_stationManagerReports);

		_reportQuarterControl.setField(_stationManagerReports.getClass().getDeclaredField("_report_quarter"));
		_reportQuarterControl.setEntity(_stationManagerReports);

		//grouping
		groupControls(new ControlAdapter[] { _amountControlSolerAmount, _amountControlMotorcyclesAmount, _amountControlBenzinAmount });

	}

	@Override
	protected void onLoad() {
		
	}

	@Override
	public void setParameters(IEntity[] entities) {
		super.setParameters(entities);
	}

	private List<QueryContainer> prepareQuery(StationsFuel stationsFuel) {
		List<QueryContainer> containers = new ArrayList<QueryContainer>();
		
		Map<String, String> queryMap = new HashMap<String, String>();
		
		QueryContainer container = new QueryContainer();
		container.setQueryEntity(stationsFuel);
		container.setQueryMap(queryMap);
		containers.add(container);
		return containers;
	}

	public StationManagerReports getStationManagerReportsSolerAmount() {
		 return _stationManagerReportsSolerAmount;
	}

	public void setStationManagerReportsSolerAmount(StationManagerReports stationManagerReportsSolerAmount) {
		 _stationManagerReportsSolerAmount = stationManagerReportsSolerAmount;
	}

	public FuelEnum getFuelEnum() {
		 return _fuelEnum;
	}

	public void setFuelEnum(FuelEnum fuelEnum) {
		 _fuelEnum = fuelEnum;
	}

	public StationManagerReports getStationManagerReportsMotorcyclesAmount() {
		 return _stationManagerReportsMotorcyclesAmount;
	}

	public void setStationManagerReportsMotorcyclesAmount(StationManagerReports stationManagerReportsMotorcyclesAmount) {
		 _stationManagerReportsMotorcyclesAmount = stationManagerReportsMotorcyclesAmount;
	}

	public StationManagerReports getStationManagerReports() {
		 return _stationManagerReports;
	}

	public void setStationManagerReports(StationManagerReports stationManagerReports) {
		 _stationManagerReports = stationManagerReports;
	}

	public Station getStation() {
		 return _station;
	}

	public void setStation(Station station) {
		 _station = station;
	}

	public StationManagerReports getStationManagerReportsBenzinAmount() {
		 return _stationManagerReportsBenzinAmount;
	}

	public void setStationManagerReportsBenzinAmount(StationManagerReports stationManagerReportsBenzinAmount) {
		 _stationManagerReportsBenzinAmount = stationManagerReportsBenzinAmount;
	}
}
