package wrapper;

import java.util.HashMap;
import java.util.Map;

import annotations.AutoGenerated;
import application.Main;
import client.IClient;
import controls.MfImageView;
import db.entity.SystemUser;
import db.interfaces.IEntity;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.image.ImageView;
import sceneswitch.SceneBase;

@AutoGenerated
public class MainMenuStationManagerScreen extends SceneBase {

	public MainMenuStationManagerScreen(ISceneSwitcher sceneSwitcher, IClient client) throws Exception {
		super(sceneSwitcher, client);
		initialize();
	}

	public void initialize() throws Exception {
		Parent root = FXMLLoader.load(Main.class.getResource("MainMenuStationManagerScreen.fxml"));
		_scene = new Scene(root);

		//scene switchers
		MfImageView fuelThresholdLevelScreenControl = new MfImageView((ImageView) _scene.lookup("#scene$FuelThresholdLevelScreen"));
		fuelThresholdLevelScreenControl.addEvent((event) -> { _switcher.switchScene("FuelThresholdLevelScreen"); });

		MfImageView ordersStationManagerScreenControl = new MfImageView((ImageView) _scene.lookup("#scene$OrdersStationManagerScreen"));
		ordersStationManagerScreenControl.addEvent((event) -> { _switcher.switchScene("OrdersStationManagerScreen"); });

		MfImageView mainMenuMyFuelScreenControl = new MfImageView((ImageView) _scene.lookup("#scene$MainMenuMyFuelScreen"));
		mainMenuMyFuelScreenControl.addEvent((event) -> { _switcher.switchScene("MainMenuMyFuelScreen"); });

		MfImageView inventoryReportScreenControl = new MfImageView((ImageView) _scene.lookup("#scene$InventoryReportScreen"));
		inventoryReportScreenControl.addEvent((event) -> { _switcher.switchScene("InventoryReportScreen"); });

		MfImageView incomeReportScreenControl = new MfImageView((ImageView) _scene.lookup("#scene$IncomeReportScreen"));
		incomeReportScreenControl.addEvent((event) -> { _switcher.switchScene("IncomeReportScreen"); });

		MfImageView expenseReportScreenControl = new MfImageView((ImageView) _scene.lookup("#scene$ExpenseReportScreen"));
		expenseReportScreenControl.addEvent((event) -> { _switcher.switchScene("ExpenseReportScreen"); });


	}
	private Map<IEntity, Map<String, String>> prepareQuery(SystemUser systemUser) {
		Map<IEntity, Map<String, String>> map = new HashMap<IEntity, Map<String, String>>();
		
		Map<String, String> queryMap = new HashMap<String, String>();
		
		map.put(systemUser, queryMap);
		return map;
	}
}
