package wrapper;

import java.util.Arrays;

import annotations.AutoGenerated;
import application.Main;
import client.IClient;
import controls.MfImageView;
import controls.MfText;
import db.interfaces.IEntity;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.image.ImageView;
import javafx.scene.text.Text;
import sceneswitch.Context;
import sceneswitch.ISceneSwitcher;
import sceneswitch.SceneBase;

@AutoGenerated
public class MainMenuMarketingNextScreen extends SceneBase {



	private MfImageView _setPriceScreenControl;
	private MfImageView _mainMenuMyFuelScreenControl;
	private MfImageView _salesManagementScreenControl;
	private MfImageView _customerCharacterizationReportScreenControl;
	private MfImageView _mainMenuMarketingScreenControl;
	private MfImageView _mainMenuMarketingNextNextScreenControl;
	private MfText _firstNameControl;
	private MfImageView _editSalesScreenControl;

	public MainMenuMarketingNextScreen(ISceneSwitcher sceneSwitcher, IClient client, Context context) throws Exception {
		super(sceneSwitcher, client, context);
	}

	@Override
	public void initialize() throws Exception {
		Parent root = FXMLLoader.load(Main.class.getResource("MainMenuMarketingNextScreen.fxml"));
		_scene = new Scene(root);

		//scene switchers
		_setPriceScreenControl = new MfImageView((ImageView) _scene.lookup("#scene$SetPriceScreen"));
		_setPriceScreenControl.addEvent((event) -> { _switcher.switchScene("SetPriceScreen"); });
		_setPriceScreenControl.getInstance().setDisable(true);

		_mainMenuMyFuelScreenControl = new MfImageView((ImageView) _scene.lookup("#scene$MainMenuMyFuelScreen"));
		_mainMenuMyFuelScreenControl.addEvent((event) -> { _switcher.switchScene("MainMenuMyFuelScreen"); });

		_salesManagementScreenControl = new MfImageView((ImageView) _scene.lookup("#scene$SalesManagementScreen"));
		_salesManagementScreenControl.addEvent((event) -> { _switcher.switchScene("SalesManagementScreen"); });
		_salesManagementScreenControl.getInstance().setDisable(true);

		_customerCharacterizationReportScreenControl = new MfImageView((ImageView) _scene.lookup("#scene$CustomerCharacterizationReportScreen"));
		_customerCharacterizationReportScreenControl.addEvent((event) -> { _switcher.switchScene("CustomerCharacterizationReportScreen"); });
		_customerCharacterizationReportScreenControl.getInstance().setDisable(true);

		_mainMenuMarketingScreenControl = new MfImageView((ImageView) _scene.lookup("#scene$MainMenuMarketingScreen"));
		_mainMenuMarketingScreenControl.addEvent((event) -> { _switcher.switchScene("MainMenuMarketingScreen"); });

		_mainMenuMarketingNextNextScreenControl = new MfImageView((ImageView) _scene.lookup("#scene$MainMenuMarketingNextNextScreen"));
		_mainMenuMarketingNextNextScreenControl.addEvent((event) -> { _switcher.switchScene("MainMenuMarketingNextNextScreen"); });

		_editSalesScreenControl = new MfImageView((ImageView) _scene.lookup("#scene$EditSalesScreen"));
		_editSalesScreenControl.addEvent((event) -> { _switcher.switchScene("EditSalesScreen"); });
		_editSalesScreenControl.getInstance().setDisable(true);

		//controls instantiation
		_firstNameControl = new MfText((Text) _scene.lookup("#context$person$first_name"));

		//fields initializations
		_firstNameControl.setField(_context.getPerson().getClass().getDeclaredField("_first_name"));
		_firstNameControl.setEntity(_context.getPerson());

		if (Arrays.asList(new String[] { 
				"Company Marketing Manager" })
				.contains(_context.getSystemUser().getPermission())) {
			_setPriceScreenControl.getInstance().setDisable(false);
		}
		if (Arrays.asList(new String[] { 
				"Company Marketing Manager" , "MyFuel Manager" })
				.contains(_context.getSystemUser().getPermission())) {
			_salesManagementScreenControl.getInstance().setDisable(false);
		}
		if (Arrays.asList(new String[] { 
				"Company Marketing Manager" , "MyFuel Manager" })
				.contains(_context.getSystemUser().getPermission())) {
			_customerCharacterizationReportScreenControl.getInstance().setDisable(false);
		}
		if (Arrays.asList(new String[] { 
				"Company Markteing Representative" , "Company Marketing Manager" })
				.contains(_context.getSystemUser().getPermission())) {
			_editSalesScreenControl.getInstance().setDisable(false);
		}
	}

	@Override
	protected void onLoad() {
		
	}

	@Override
	public void setParameters(IEntity[] entities) {
		super.setParameters(entities);
	}



}
