package wrapper;

import javafx.scene.layout.BorderPane;
import javafx.fxml.FXMLLoader;
import db.entity.*;
import adapter.base.ControlAdapter;
import java.util.HashSet;
import widgets.table.Table;
import application.Main;
import controls.*;
import annotations.AutoGenerated;
import java.util.HashMap;
import javafx.scene.Parent;
import sceneswitch.SceneBase;
import java.util.Map;
import java.util.Collection;
import table.MfTable;
import widgets.table.*;
import client.IClient;

import javafx.scene.Scene;
import javafx.scene.control.*;
import action.*;
import db.interfaces.IEntity;
import javafx.scene.image.ImageView;
import java.util.Set;
import javafx.scene.text.Text;

@AutoGenerated
public class MainMenuMyFuelScreen extends SceneBase {

	public MainMenuMyFuelScreen(ISceneSwitcher sceneSwitcher, IClient client) throws Exception {
		super(sceneSwitcher, client);
		initialize();
	}

	public void initialize() throws Exception {
		Parent root = FXMLLoader.load(Main.class.getResource("MainMenuMyFuelScreen.fxml"));
		_scene = new Scene(root);

		//scene switchers
		MfImageView aboutUsScreenControl = new MfImageView((ImageView) _scene.lookup("#scene$AboutUsScreen"));
		aboutUsScreenControl.addEvent((event) -> { _switcher.switchScene("AboutUsScreen"); });

		MfImageView signUpPersonalDetailsScreenControl = new MfImageView((ImageView) _scene.lookup("#scene$SignUpPersonalDetailsScreen"));
		signUpPersonalDetailsScreenControl.addEvent((event) -> { _switcher.switchScene("SignUpPersonalDetailsScreen"); });

		MfImageView logInScreenControl = new MfImageView((ImageView) _scene.lookup("#scene$LogInScreen"));
		logInScreenControl.addEvent((event) -> { _switcher.switchScene("LogInScreen"); });


	}
	private Map<IEntity, Map<String, String>> prepareQuery(SystemUser systemUser) {
		Map<IEntity, Map<String, String>> map = new HashMap<IEntity, Map<String, String>>();
		
		Map<String, String> queryMap = new HashMap<String, String>();
		
		map.put(systemUser, queryMap);
		return map;
	}
}
