package wrapper;

import javafx.scene.layout.BorderPane;
import javafx.fxml.FXMLLoader;
import db.entity.*;
import adapter.base.ControlAdapter;
import java.util.HashSet;
import widgets.table.Table;
import application.Main;
import controls.*;
import annotations.AutoGenerated;
import java.util.HashMap;
import javafx.scene.Parent;
import sceneswitch.SceneBase;
import java.util.Map;
import java.util.Collection;
import table.MfTable;
import widgets.table.*;
import client.IClient;

import javafx.scene.Scene;
import javafx.scene.control.*;
import action.*;
import db.interfaces.IEntity;
import javafx.scene.image.ImageView;
import java.util.Set;
import javafx.scene.text.Text;

@AutoGenerated
public class MainMenuMarketingScreen extends SceneBase {

	public MainMenuMarketingScreen(ISceneSwitcher sceneSwitcher, IClient client) throws Exception {
		super(sceneSwitcher, client);
		initialize();
	}

	public void initialize() throws Exception {
		Parent root = FXMLLoader.load(Main.class.getResource("MainMenuMarketingScreen.fxml"));
		_scene = new Scene(root);

		//scene switchers
		MfImageView pricingModelMatchingScreenControl = new MfImageView((ImageView) _scene.lookup("#scene$PricingModelMatchingScreen"));
		pricingModelMatchingScreenControl.addEvent((event) -> { _switcher.switchScene("PricingModelMatchingScreen"); });

		MfImageView customerManagementScreenControl = new MfImageView((ImageView) _scene.lookup("#scene$CustomerManagementScreen"));
		customerManagementScreenControl.addEvent((event) -> { _switcher.switchScene("CustomerManagementScreen"); });

		MfImageView salesManagementScreenControl = new MfImageView((ImageView) _scene.lookup("#scene$SalesManagementScreen"));
		salesManagementScreenControl.addEvent((event) -> { _switcher.switchScene("SalesManagementScreen"); });

		MfImageView signUpPersonDetailsScreenControl = new MfImageView((ImageView) _scene.lookup("#scene$SignUpPersonDetailsScreen"));
		signUpPersonDetailsScreenControl.addEvent((event) -> { _switcher.switchScene("SignUpPersonDetailsScreen"); });

		MfImageView purchasePlanMatchingScreenControl = new MfImageView((ImageView) _scene.lookup("#scene$PurchasePlanMatchingScreen"));
		purchasePlanMatchingScreenControl.addEvent((event) -> { _switcher.switchScene("PurchasePlanMatchingScreen"); });

		MfImageView setPriceScreenControl = new MfImageView((ImageView) _scene.lookup("#scene$SetPriceScreen"));
		setPriceScreenControl.addEvent((event) -> { _switcher.switchScene("SetPriceScreen"); });

		MfImageView mainMenuMyFuelScreenControl = new MfImageView((ImageView) _scene.lookup("#scene$MainMenuMyFuelScreen"));
		mainMenuMyFuelScreenControl.addEvent((event) -> { _switcher.switchScene("MainMenuMyFuelScreen"); });


	}
	private Map<IEntity, Map<String, String>> prepareQuery(SystemUser systemUser) {
		Map<IEntity, Map<String, String>> map = new HashMap<IEntity, Map<String, String>>();
		
		Map<String, String> queryMap = new HashMap<String, String>();
		
		map.put(systemUser, queryMap);
		return map;
	}
}
