package wrapper;

import annotations.AutoGenerated;
import application.Main;
import client.IClient;
import controls.MfImageView;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.image.ImageView;
import sceneswitch.Context;
import sceneswitch.SceneBase;

@AutoGenerated
public class MainMenuMarketingScreen extends SceneBase {



	private MfImageView _pricingModelMatchingScreenControl;
	private MfImageView _customerManagementScreenControl;
	private MfImageView _salesManagementScreenControl;
	private MfImageView _signUpPersonalDetailsScreenControl;
	private MfImageView _purchasePlanMatchingScreenControl;
	private MfImageView _setPriceScreenControl;
	private MfImageView _mainMenuMyFuelScreenControl;

	public MainMenuMarketingScreen(ISceneSwitcher sceneSwitcher, IClient client, Context context) throws Exception {
		super(sceneSwitcher, client, context);
		initialize();
	}

	public void initialize() throws Exception {
		Parent root = FXMLLoader.load(Main.class.getResource("MainMenuMarketingScreen.fxml"));
		_scene = new Scene(root);

		//scene switchers
		_pricingModelMatchingScreenControl = new MfImageView((ImageView) _scene.lookup("#scene$PricingModelMatchingScreen"));
		_pricingModelMatchingScreenControl.addEvent((event) -> { _switcher.switchScene("PricingModelMatchingScreen"); });

		_customerManagementScreenControl = new MfImageView((ImageView) _scene.lookup("#scene$CustomerManagementScreen"));
		_customerManagementScreenControl.addEvent((event) -> { _switcher.switchScene("CustomerManagementScreen"); });

		_salesManagementScreenControl = new MfImageView((ImageView) _scene.lookup("#scene$SalesManagementScreen"));
		_salesManagementScreenControl.addEvent((event) -> { _switcher.switchScene("SalesManagementScreen"); });

		_signUpPersonalDetailsScreenControl = new MfImageView((ImageView) _scene.lookup("#scene$SignUpPersonalDetailsScreen"));
		_signUpPersonalDetailsScreenControl.addEvent((event) -> { _switcher.switchScene("SignUpPersonalDetailsScreen"); });

		_purchasePlanMatchingScreenControl = new MfImageView((ImageView) _scene.lookup("#scene$PurchasePlanMatchingScreen"));
		_purchasePlanMatchingScreenControl.addEvent((event) -> { _switcher.switchScene("PurchasePlanMatchingScreen"); });

		_setPriceScreenControl = new MfImageView((ImageView) _scene.lookup("#scene$SetPriceScreen"));
		_setPriceScreenControl.addEvent((event) -> { _switcher.switchScene("SetPriceScreen"); });

		_mainMenuMyFuelScreenControl = new MfImageView((ImageView) _scene.lookup("#scene$MainMenuMyFuelScreen"));
		_mainMenuMyFuelScreenControl.addEvent((event) -> { _switcher.switchScene("MainMenuMyFuelScreen"); });


	}



}
