package wrapper;

import annotations.AutoGenerated;
import application.Main;
import client.IClient;
import controls.MfImageView;
import controls.MfText;
import db.interfaces.IEntity;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.image.ImageView;
import javafx.scene.text.Text;
import sceneswitch.Context;
import sceneswitch.ISceneSwitcher;
import sceneswitch.SceneBase;

@AutoGenerated
public class MainMenuCompanyManagerScreen extends SceneBase {



	private MfImageView _fuelPriceApprovalScreenControl;
	private MfImageView _inventoryReportScreenControl;
	private MfImageView _incomeReportScreenControl;
	private MfImageView _expenseReportScreenControl;
	private MfImageView _mainMenuMyFuelScreenControl;
	private MfText _firstNameControl;

	public MainMenuCompanyManagerScreen(ISceneSwitcher sceneSwitcher, IClient client, Context context) throws Exception {
		super(sceneSwitcher, client, context);
	}

	@Override
	public void initialize() throws Exception {
		Parent root = FXMLLoader.load(Main.class.getResource("MainMenuCompanyManagerScreen.fxml"));
		_scene = new Scene(root);

		//scene switchers
		_fuelPriceApprovalScreenControl = new MfImageView((ImageView) _scene.lookup("#scene$FuelDiscountApprovalScreen"));
		_fuelPriceApprovalScreenControl.addEvent((event) -> { _switcher.switchScene("FuelDiscountApprovalScreen"); });

		_inventoryReportScreenControl = new MfImageView((ImageView) _scene.lookup("#scene$CompanyManagerInventoryScreen"));
		_inventoryReportScreenControl.addEvent((event) -> { _switcher.switchScene("CompanyManagerInventoryScreen"); });

		_incomeReportScreenControl = new MfImageView((ImageView) _scene.lookup("#scene$CompanyManagerIncomeReportScreen"));
		_incomeReportScreenControl.addEvent((event) -> { _switcher.switchScene("CompanyManagerIncomeReportScreen"); });

		_expenseReportScreenControl = new MfImageView((ImageView) _scene.lookup("#scene$CompanyManagerExpenseReportScreen"));
		_expenseReportScreenControl.addEvent((event) -> { _switcher.switchScene("CompanyManagerExpenseReportScreen"); });

		_mainMenuMyFuelScreenControl = new MfImageView((ImageView) _scene.lookup("#scene$MainMenuMyFuelScreen"));
		_mainMenuMyFuelScreenControl.addEvent((event) -> { _switcher.switchScene("MainMenuMyFuelScreen"); });

		//controls instantiation
		_firstNameControl = new MfText((Text) _scene.lookup("#context$person$first_name"));

		//fields initializations
		_firstNameControl.setField(_context.getPerson().getClass().getDeclaredField("_first_name"));
		_firstNameControl.setEntity(_context.getPerson());


	}

	@Override
	protected void onLoad() {
		
	}

	@Override
	public void setParameters(IEntity[] entities) {
		super.setParameters(entities);
	}



}
