package wrapper;

import annotations.AutoGenerated;
import application.Main;
import client.IClient;
import controls.MfImageView;
import controls.MfText;
import db.interfaces.IEntity;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.image.ImageView;
import javafx.scene.text.Text;
import sceneswitch.Context;
import sceneswitch.ISceneSwitcher;
import sceneswitch.SceneBase;

@AutoGenerated
public class MainMenuSupplierScreen extends SceneBase {



	private MfImageView _homeHeatingManagementScreenControl;
	private MfImageView _stationSupplyOrdersScreenControl;
	private MfImageView _mainMenuMyFuelScreenControl;
	private MfText _firstNameControl;

	public MainMenuSupplierScreen(ISceneSwitcher sceneSwitcher, IClient client, Context context) throws Exception {
		super(sceneSwitcher, client, context);
	}

	@Override
	public void initialize() throws Exception {
		Parent root = FXMLLoader.load(Main.class.getResource("MainMenuSupplierScreen.fxml"));
		_scene = new Scene(root);

		//scene switchers
		_homeHeatingManagementScreenControl = new MfImageView((ImageView) _scene.lookup("#scene$HomeHeatingManagementScreen"));
		_homeHeatingManagementScreenControl.addEvent((event) -> { _switcher.switchScene("HomeHeatingManagementScreen"); });

		_stationSupplyOrdersScreenControl = new MfImageView((ImageView) _scene.lookup("#scene$StationSupplyOrdersScreen"));
		_stationSupplyOrdersScreenControl.addEvent((event) -> { _switcher.switchScene("StationSupplyOrdersScreen"); });

		_mainMenuMyFuelScreenControl = new MfImageView((ImageView) _scene.lookup("#scene$MainMenuMyFuelScreen"));
		_mainMenuMyFuelScreenControl.addEvent((event) -> { _switcher.switchScene("MainMenuMyFuelScreen"); });

		//controls instantiation
		_firstNameControl = new MfText((Text) _scene.lookup("#context$person$first_name"));

		//fields initializations
		_firstNameControl.setField(_context.getPerson().getClass().getDeclaredField("_first_name"));
		_firstNameControl.setEntity(_context.getPerson());


	}

	@Override
	protected void onLoad() {
		
	}

	@Override
	public void setParameters(IEntity[] entities) {
		super.setParameters(entities);
	}



}
