package wrapper;

import java.util.ArrayList;
import java.util.Collection;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import action.ActionControl;
import action.FilterCapability;
import action.UpdateCapability;
import annotations.AutoGenerated;
import application.Main;
import client.IClient;
import controls.MfImageView;
import controls.MfListView;
import controls.MfMenuButton;
import controls.MfText;
import controls.MfTextField;
import db.entity.Car;
import db.entity.Customer;
import db.entity.Person;
import db.entity.PricingModelEnum;
import db.interfaces.IEntity;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.ListView;
import javafx.scene.control.MenuButton;
import javafx.scene.control.TextField;
import javafx.scene.image.ImageView;
import javafx.scene.layout.BorderPane;
import javafx.scene.text.Text;
import messages.QueryContainer;
import sceneswitch.Context;
import sceneswitch.SceneBase;
import table.MfTable;
import widgets.table.MfSingleDecorator;
import widgets.table.Table;

@AutoGenerated
public class PricingModelMatchingScreen extends SceneBase {

	private Customer _customer;
	private PricingModelEnum _pricingModelEnum;
	private Car _car;
	private Person _person;

	private MfTextField _customerIdControl;
	private Table<PricingModelEnum> _pricingModelEnumTableWrapper;
	private MfTable<PricingModelEnum> _pricingModelEnumTable;
	private MfListView _plateNumberControl;
	private MfMenuButton _modelTypeKeyControl;
	private MfImageView _mainMenuMarketingScreenControl;
	private MfImageView _filterCustomerControl;
	private ActionControl _customerfilterAction;
	private MfImageView _updatePricingModelEnumControl;
	private ActionControl _pricingModelEnumupdateAction;
	private MfText _firstNameControl;
	private MfText _emailControl;
	private MfText _phoneNumberControl;
	private MfText _lastNameControl;

	public PricingModelMatchingScreen(ISceneSwitcher sceneSwitcher, IClient client, Context context) throws Exception {
		super(sceneSwitcher, client, context);
		initialize();
	}

	public void initialize() throws Exception {
		Parent root = FXMLLoader.load(Main.class.getResource("PricingModelMatchingScreen.fxml"));
		_scene = new Scene(root);

		//scene switchers
		_mainMenuMarketingScreenControl = new MfImageView((ImageView) _scene.lookup("#scene$MainMenuMarketingScreen"));
		_mainMenuMarketingScreenControl.addEvent((event) -> { _switcher.switchScene("MainMenuMarketingScreen"); });

		//entities instantiation
		_customer = new Customer();
		_pricingModelEnum = new PricingModelEnum();
		_car = new Car();
		_person = new Person();

		//entities assignments
		_car.setCustomer(_customer);
		_customer.setPerson(_person);

		//controls instantiation
		_customerIdControl = new MfTextField((TextField) _scene.lookup("#table$customer$customer_id"));
		_plateNumberControl = new MfListView((ListView) _scene.lookup("#table$customer$car$plate_number"));
		_modelTypeKeyControl = new MfMenuButton((MenuButton) _scene.lookup("#table$pricing_model_enum$model_type_key"));
		_firstNameControl = new MfText((Text) _scene.lookup("#table$customer$person$first_name"));
		_emailControl = new MfText((Text) _scene.lookup("#table$customer$person$email"));
		_phoneNumberControl = new MfText((Text) _scene.lookup("#table$customer$person$phone_number"));
		_lastNameControl = new MfText((Text) _scene.lookup("#table$customer$person$last_name"));

		//tables instantiation
		BorderPane pricingModelEnumBp = (BorderPane) _scene.lookup("#uitable$noneditable$single$pricing_model_enum");
		_pricingModelEnumTableWrapper = new Table<PricingModelEnum>();
		_pricingModelEnumTable = new MfTable<PricingModelEnum>(PricingModelEnum.class);
		_pricingModelEnumTable.setEditable(false);
		MfSingleDecorator<PricingModelEnum> pricingModelEnumSingleDecorator = new MfSingleDecorator<PricingModelEnum>();
		_pricingModelEnumTableWrapper.addDecorator(pricingModelEnumSingleDecorator);
		_pricingModelEnumTableWrapper.setTable(_pricingModelEnumTable);
		pricingModelEnumBp.setCenter(_pricingModelEnumTable);

		//initializations
		_filterCustomerControl = new MfImageView((ImageView) _scene.lookup("#action$collect$customer"));
		_customerfilterAction = new ActionControl();
		_customerfilterAction.setControl(_filterCustomerControl);
		FilterCapability customerFilterCapability = new FilterCapability();
		customerFilterCapability.setQueryContainers(prepareQuery(_customer));
		_customerfilterAction.addCapability(customerFilterCapability);
		_customerfilterAction.setClient(_client);
		_customerfilterAction.setCallback((response) -> {
			Collection<IEntity> entities = response.getEntities();
			for (IEntity ientity : entities) {
				Customer entity = (Customer) ientity;
			}
		});

		_updatePricingModelEnumControl = new MfImageView((ImageView) _scene.lookup("#action$update$customer$pricing_model_enum"));
		_pricingModelEnumupdateAction = new ActionControl();
		_pricingModelEnumupdateAction.setControl(_updatePricingModelEnumControl);
		UpdateCapability pricingModelEnumUpdateCapability = new UpdateCapability();
		Set<IEntity> pricingModelEnumUpdateEntities = new HashSet<IEntity>();
		pricingModelEnumUpdateCapability.setEntities(pricingModelEnumUpdateEntities);
		_pricingModelEnumupdateAction.addCapability(pricingModelEnumUpdateCapability);
		_pricingModelEnumupdateAction.setClient(_client);
		_pricingModelEnumupdateAction.setCallback((response) -> {
			
		});

		//fields initializations
		_customerIdControl.setField(_customer.getClass().getDeclaredField("_customer_id"));
		_customerIdControl.setEntity(_customer);

		_plateNumberControl.setField(_car.getClass().getDeclaredField("_plate_number"));
		_plateNumberControl.setEntity(_car);

		_modelTypeKeyControl.setField(_pricingModelEnum.getClass().getDeclaredField("_model_type_key"));
		_modelTypeKeyControl.setEntity(_pricingModelEnum);

		_firstNameControl.setField(_person.getClass().getDeclaredField("_first_name"));
		_firstNameControl.setEntity(_person);

		_emailControl.setField(_person.getClass().getDeclaredField("_email"));
		_emailControl.setEntity(_person);

		_phoneNumberControl.setField(_person.getClass().getDeclaredField("_phone_number"));
		_phoneNumberControl.setEntity(_person);

		_lastNameControl.setField(_person.getClass().getDeclaredField("_last_name"));
		_lastNameControl.setEntity(_person);


	}

	private List<QueryContainer> prepareQuery(Customer customer) {
		List<QueryContainer> containers = new ArrayList<QueryContainer>();
		
		Map<String, String> queryMap = new HashMap<String, String>();
		
		QueryContainer container = new QueryContainer();
		container.setQueryEntity(customer);
		container.setQueryMap(queryMap);
		containers.add(container);
		return containers;
	}

	public Customer getCustomer() {
		 return _customer;
	}

	public void setCustomer(Customer customer) {
		 _customer = customer;
	}

	public Car getCar() {
		 return _car;
	}

	public void setCar(Car car) {
		 _car = car;
	}

	public PricingModelEnum getPricingModelEnum() {
		 return _pricingModelEnum;
	}

	public void setPricingModelEnum(PricingModelEnum pricingModelEnum) {
		 _pricingModelEnum = pricingModelEnum;
	}

	public Person getPerson() {
		 return _person;
	}

	public void setPerson(Person person) {
		 _person = person;
	}
}
