package wrapper;

import java.util.ArrayList;
import java.util.Collection;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import action.ActionControl;
import action.FilterCapability;
import action.UpdateCapability;
import adapter.base.ControlAdapter;
import annotations.AutoGenerated;
import application.Main;
import client.IClient;
import controls.MfComboBox;
import controls.MfImageView;
import controls.MfText;
import controls.MfTextField;
import db.entity.Customer;
import db.entity.FuelCompanyEnum;
import db.entity.Person;
import db.entity.SubscriptionPlan;
import db.entity.SubscriptionPlanRatesEnum;
import db.interfaces.IEntity;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.ComboBox;
import javafx.scene.control.TextField;
import javafx.scene.image.ImageView;
import javafx.scene.text.Text;
import messages.QueryContainer;
import sceneswitch.Context;
import sceneswitch.SceneBase;

@AutoGenerated
public class PurchasePlanMatchingScreen extends SceneBase {

	private Customer _customer;
	private SubscriptionPlan _subscriptionPlan;
	private FuelCompanyEnum _fuelCompanyEnum;
	private SubscriptionPlanRatesEnum _subscriptionPlanRatesEnum;
	private Person _person;

	private MfTextField _customerIdControl;
	private MfComboBox _companyNameKeyControlCmb;
	private MfImageView _mainMenuMarketingScreenControl;
	private MfImageView _filterCustomerControl;
	private ActionControl _customerfilterAction;
	private MfImageView _updateSubscriptionPlanControl;
	private ActionControl _subscriptionPlanupdateAction;
	private MfText _companyNameKeyControlTxt1;
	private MfText _companyNameKeyControlTxt2;
	private MfText _companyNameKeyControlTxt3;
	private MfComboBox _companyNameKeyControlCmb1;
	private MfComboBox _companyNameKeyControlCmb2;
	private MfText _planTypeKeyControl;
	private MfText _firstNameControl;
	private MfText _emailControl;
	private MfText _phoneNumberControl;

	public PurchasePlanMatchingScreen(ISceneSwitcher sceneSwitcher, IClient client, Context context) throws Exception {
		super(sceneSwitcher, client, context);
		initialize();
	}

	public void initialize() throws Exception {
		Parent root = FXMLLoader.load(Main.class.getResource("PurchasePlanMatchingScreen.fxml"));
		_scene = new Scene(root);

		//scene switchers
		_mainMenuMarketingScreenControl = new MfImageView((ImageView) _scene.lookup("#scene$MainMenuMarketingScreen"));
		_mainMenuMarketingScreenControl.addEvent((event) -> { _switcher.switchScene("MainMenuMarketingScreen"); });

		//entities instantiation
		_customer = new Customer();
		_subscriptionPlan = new SubscriptionPlan();
		_fuelCompanyEnum = new FuelCompanyEnum();
		_subscriptionPlanRatesEnum = new SubscriptionPlanRatesEnum();
		_person = new Person();

		//entities assignments
		_subscriptionPlan.setFuelCompanyEnum(_fuelCompanyEnum);
		_subscriptionPlan.setSubscriptionPlanRatesEnum(_subscriptionPlanRatesEnum);
		_customer.setPerson(_person);

		//controls instantiation
		_customerIdControl = new MfTextField((TextField) _scene.lookup("#table$customer$customer_id"));
		_companyNameKeyControlCmb = new MfComboBox((ComboBox) _scene.lookup("#table$subscription_plan$fuel_company_enum$company_name_key$$$cmb"));
		_companyNameKeyControlTxt1 = new MfText((Text) _scene.lookup("#table$subscription_plan$fuel_company_enum$company_name_key$$$txt1"));
		_companyNameKeyControlTxt2 = new MfText((Text) _scene.lookup("#table$subscription_plan$fuel_company_enum$company_name_key$$$txt2"));
		_companyNameKeyControlTxt3 = new MfText((Text) _scene.lookup("#table$subscription_plan$fuel_company_enum$company_name_key$$$txt3"));
		_companyNameKeyControlCmb1 = new MfComboBox((ComboBox) _scene.lookup("#table$subscription_plan$fuel_company_enum$company_name_key$$$cmb1"));
		_companyNameKeyControlCmb2 = new MfComboBox((ComboBox) _scene.lookup("#table$subscription_plan$fuel_company_enum$company_name_key$$$cmb2"));
		_planTypeKeyControl = new MfText((Text) _scene.lookup("#table$subscription_plan$subscription_plan_rates_enum$plan_type_key"));
		_firstNameControl = new MfText((Text) _scene.lookup("#table$customer$person$first_name"));
		_emailControl = new MfText((Text) _scene.lookup("#table$customer$person$email"));
		_phoneNumberControl = new MfText((Text) _scene.lookup("#table$customer$person$phone_number"));

		//initializations
		_filterCustomerControl = new MfImageView((ImageView) _scene.lookup("#action$collect$customer"));
		_customerfilterAction = new ActionControl();
		_customerfilterAction.setControl(_filterCustomerControl);
		FilterCapability customerFilterCapability = new FilterCapability();
		customerFilterCapability.setQueryContainers(prepareQuery(_customer));
		_customerfilterAction.addCapability(customerFilterCapability);
		_customerfilterAction.setClient(_client);
		_customerfilterAction.setCallback((response) -> {
			Collection<IEntity> entities = response.getEntities();
			for (IEntity ientity : entities) {
				Customer entity = (Customer) ientity;
			}
		});

		_updateSubscriptionPlanControl = new MfImageView((ImageView) _scene.lookup("#action$update$subscription_plan"));
		_subscriptionPlanupdateAction = new ActionControl();
		_subscriptionPlanupdateAction.setControl(_updateSubscriptionPlanControl);
		UpdateCapability subscriptionPlanUpdateCapability = new UpdateCapability();
		Set<IEntity> subscriptionPlanUpdateEntities = new HashSet<IEntity>();
		subscriptionPlanUpdateCapability.setEntities(subscriptionPlanUpdateEntities);
		_subscriptionPlanupdateAction.addCapability(subscriptionPlanUpdateCapability);
		_subscriptionPlanupdateAction.setClient(_client);
		_subscriptionPlanupdateAction.setCallback((response) -> {
			
		});

		//fields initializations
		_customerIdControl.setField(_customer.getClass().getDeclaredField("_customer_id"));
		_customerIdControl.setEntity(_customer);

		_companyNameKeyControlCmb.setField(_fuelCompanyEnum.getClass().getDeclaredField("_company_name_key"));
		_companyNameKeyControlCmb.setEntity(_fuelCompanyEnum);

		_companyNameKeyControlTxt1.setField(_fuelCompanyEnum.getClass().getDeclaredField("_company_name_key"));
		_companyNameKeyControlTxt1.setEntity(_fuelCompanyEnum);

		_companyNameKeyControlTxt2.setField(_fuelCompanyEnum.getClass().getDeclaredField("_company_name_key"));
		_companyNameKeyControlTxt2.setEntity(_fuelCompanyEnum);

		_companyNameKeyControlTxt3.setField(_fuelCompanyEnum.getClass().getDeclaredField("_company_name_key"));
		_companyNameKeyControlTxt3.setEntity(_fuelCompanyEnum);

		_companyNameKeyControlCmb1.setField(_fuelCompanyEnum.getClass().getDeclaredField("_company_name_key"));
		_companyNameKeyControlCmb1.setEntity(_fuelCompanyEnum);

		_companyNameKeyControlCmb2.setField(_fuelCompanyEnum.getClass().getDeclaredField("_company_name_key"));
		_companyNameKeyControlCmb2.setEntity(_fuelCompanyEnum);

		_planTypeKeyControl.setField(_subscriptionPlanRatesEnum.getClass().getDeclaredField("_plan_type_key"));
		_planTypeKeyControl.setEntity(_subscriptionPlanRatesEnum);

		_firstNameControl.setField(_person.getClass().getDeclaredField("_first_name"));
		_firstNameControl.setEntity(_person);

		_emailControl.setField(_person.getClass().getDeclaredField("_email"));
		_emailControl.setEntity(_person);

		_phoneNumberControl.setField(_person.getClass().getDeclaredField("_phone_number"));
		_phoneNumberControl.setEntity(_person);

		//grouping
		groupControls(new ControlAdapter[] { _companyNameKeyControlCmb, _companyNameKeyControlTxt1, _companyNameKeyControlTxt2, _companyNameKeyControlTxt3, _companyNameKeyControlCmb1, _companyNameKeyControlCmb2 });

	}

	private List<QueryContainer> prepareQuery(Customer customer) {
		List<QueryContainer> containers = new ArrayList<QueryContainer>();
		
		Map<String, String> queryMap = new HashMap<String, String>();
		
		QueryContainer container = new QueryContainer();
		container.setQueryEntity(customer);
		container.setQueryMap(queryMap);
		containers.add(container);
		return containers;
	}

	public Customer getCustomer() {
		 return _customer;
	}

	public void setCustomer(Customer customer) {
		 _customer = customer;
	}

	public SubscriptionPlan getSubscriptionPlan() {
		 return _subscriptionPlan;
	}

	public void setSubscriptionPlan(SubscriptionPlan subscriptionPlan) {
		 _subscriptionPlan = subscriptionPlan;
	}

	public FuelCompanyEnum getFuelCompanyEnum() {
		 return _fuelCompanyEnum;
	}

	public void setFuelCompanyEnum(FuelCompanyEnum fuelCompanyEnum) {
		 _fuelCompanyEnum = fuelCompanyEnum;
	}

	public SubscriptionPlanRatesEnum getSubscriptionPlanRatesEnum() {
		 return _subscriptionPlanRatesEnum;
	}

	public void setSubscriptionPlanRatesEnum(SubscriptionPlanRatesEnum subscriptionPlanRatesEnum) {
		 _subscriptionPlanRatesEnum = subscriptionPlanRatesEnum;
	}

	public Person getPerson() {
		 return _person;
	}

	public void setPerson(Person person) {
		 _person = person;
	}
}
