package wrapper;

import java.util.HashSet;
import java.util.Set;

import action.ActionControl;
import action.UpdateCapability;
import annotations.AutoGenerated;
import application.Main;
import client.IClient;
import controls.MfImageView;
import controls.MfTextField;
import db.entity.SpecialSalesEnum;
import db.entity.SpecialSalesHistory;
import db.interfaces.IEntity;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.TextField;
import javafx.scene.image.ImageView;
import javafx.scene.layout.BorderPane;
import sceneswitch.Context;
import sceneswitch.SceneBase;
import table.MfTable;
import widgets.table.MfSingleDecorator;
import widgets.table.Table;

@AutoGenerated
public class SalesManagementScreen extends SceneBase {

	private SpecialSalesEnum _specialSalesEnum;
	private SpecialSalesHistory _specialSalesHistory;

	private MfImageView _mainMenuMarketingScreenControl;
	private Table<SpecialSalesEnum> _specialSalesEnumTableWrapper;
	private MfTable<SpecialSalesEnum> _specialSalesEnumTable;
	private MfImageView _updateSpecialSalesEnumControl;
	private ActionControl _specialSalesEnumupdateAction;
	private MfImageView _saleReportScreenControl;
	private MfImageView _editSalesScreenControl;
	private MfTextField _endTimeControl;
	private MfTextField _startTimeControl;

	public SalesManagementScreen(ISceneSwitcher sceneSwitcher, IClient client, Context context) throws Exception {
		super(sceneSwitcher, client, context);
		initialize();
	}

	public void initialize() throws Exception {
		Parent root = FXMLLoader.load(Main.class.getResource("SalesManagementScreen.fxml"));
		_scene = new Scene(root);

		//scene switchers
		_mainMenuMarketingScreenControl = new MfImageView((ImageView) _scene.lookup("#scene$MainMenuMarketingScreen"));
		_mainMenuMarketingScreenControl.addEvent((event) -> { _switcher.switchScene("MainMenuMarketingScreen"); });

		_saleReportScreenControl = new MfImageView((ImageView) _scene.lookup("#scene$SaleReportScreen"));
		_saleReportScreenControl.addEvent((event) -> { _switcher.switchScene("SaleReportScreen"); });

		_editSalesScreenControl = new MfImageView((ImageView) _scene.lookup("#scene$EditSalesScreen"));
		_editSalesScreenControl.addEvent((event) -> { _switcher.switchScene("EditSalesScreen"); });

		//entities instantiation
		_specialSalesEnum = new SpecialSalesEnum();
		_specialSalesHistory = new SpecialSalesHistory();

		//entities assignments
		_specialSalesHistory.setSpecialSalesEnum(_specialSalesEnum);

		//controls instantiation
		_endTimeControl = new MfTextField((TextField) _scene.lookup("#table$special_sales_enum$special_sales_history$end_time"));
		_startTimeControl = new MfTextField((TextField) _scene.lookup("#table$special_sales_enum$special_sales_history$start_time"));

		//tables instantiation
		BorderPane specialSalesEnumBp = (BorderPane) _scene.lookup("#uitable$editable$single$special_sales_enum");
		_specialSalesEnumTableWrapper = new Table<SpecialSalesEnum>();
		_specialSalesEnumTable = new MfTable<SpecialSalesEnum>(SpecialSalesEnum.class);
		_specialSalesEnumTable.setEditable(true);
		MfSingleDecorator<SpecialSalesEnum> specialSalesEnumSingleDecorator = new MfSingleDecorator<SpecialSalesEnum>();
		_specialSalesEnumTableWrapper.addDecorator(specialSalesEnumSingleDecorator);
		_specialSalesEnumTableWrapper.setTable(_specialSalesEnumTable);
		specialSalesEnumBp.setCenter(_specialSalesEnumTable);

		//initializations
		_updateSpecialSalesEnumControl = new MfImageView((ImageView) _scene.lookup("#action$update$special_sales_enum"));
		_specialSalesEnumupdateAction = new ActionControl();
		_specialSalesEnumupdateAction.setControl(_updateSpecialSalesEnumControl);
		UpdateCapability specialSalesEnumUpdateCapability = new UpdateCapability();
		Set<IEntity> specialSalesEnumUpdateEntities = new HashSet<IEntity>();
		specialSalesEnumUpdateCapability.setEntities(specialSalesEnumUpdateEntities);
		_specialSalesEnumupdateAction.addCapability(specialSalesEnumUpdateCapability);
		_specialSalesEnumupdateAction.setClient(_client);
		_specialSalesEnumupdateAction.setCallback((response) -> {
			
		});

		//fields initializations
		_endTimeControl.setField(_specialSalesHistory.getClass().getDeclaredField("_end_time"));
		_endTimeControl.setEntity(_specialSalesHistory);

		_startTimeControl.setField(_specialSalesHistory.getClass().getDeclaredField("_start_time"));
		_startTimeControl.setEntity(_specialSalesHistory);


	}


	public SpecialSalesEnum getSpecialSalesEnum() {
		 return _specialSalesEnum;
	}

	public void setSpecialSalesEnum(SpecialSalesEnum specialSalesEnum) {
		 _specialSalesEnum = specialSalesEnum;
	}

	public SpecialSalesHistory getSpecialSalesHistory() {
		 return _specialSalesHistory;
	}

	public void setSpecialSalesHistory(SpecialSalesHistory specialSalesHistory) {
		 _specialSalesHistory = specialSalesHistory;
	}
}
