package wrapper;

import java.util.HashSet;
import java.util.Set;

import action.ActionControl;
import action.UpdateCapability;
import adapter.base.ControlAdapter;
import annotations.AutoGenerated;
import application.Main;
import client.IClient;
import controls.MfComboBox;
import controls.MfImageView;
import controls.MfText;
import controls.MfTextField;
import db.entity.FuelCompanyEnum;
import db.entity.FuelEnum;
import db.entity.FuelInCompany;
import db.interfaces.IEntity;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.ComboBox;
import javafx.scene.control.TextField;
import javafx.scene.image.ImageView;
import javafx.scene.text.Text;
import sceneswitch.Context;
import sceneswitch.SceneBase;

@AutoGenerated
public class SetPriceScreen extends SceneBase {

	private FuelCompanyEnum _fuelCompanyEnum;
	private FuelInCompany _fuelInCompanyMotorcycleCompanyPrice;
	private FuelInCompany _fuelInCompany;
	private FuelEnum _fuelEnumMotorcycleMaxPricePerType;
	private FuelInCompany _fuelInCompanySolerCompanyPrice;
	private FuelEnum _fuelEnumSolerMaxPricePerType;
	private FuelInCompany _fuelInCompanyBenzinCompanyPrice;
	private FuelEnum _fuelEnumBenzinMaxPricePerType;

	private MfTextField _companyPriceControlMotorcycleCompanyPrice;
	private MfImageView _mainMenuMarketingScreenControl;
	private MfComboBox _companyNameKeyControl;
	private MfText _maxPricePerTypeControlMotorcycleMaxPricePerType;
	private MfImageView _updateFuelInCompanyControl;
	private ActionControl _fuelInCompanyupdateAction;
	private MfTextField _companyPriceControlSolerCompanyPrice;
	private MfText _maxPricePerTypeControlSolerMaxPricePerType;
	private MfTextField _companyPriceControlBenzinCompanyPrice;
	private MfText _maxPricePerTypeControlBenzinMaxPricePerType;

	public SetPriceScreen(ISceneSwitcher sceneSwitcher, IClient client, Context context) throws Exception {
		super(sceneSwitcher, client, context);
		initialize();
	}

	public void initialize() throws Exception {
		Parent root = FXMLLoader.load(Main.class.getResource("SetPriceScreen.fxml"));
		_scene = new Scene(root);

		//scene switchers
		_mainMenuMarketingScreenControl = new MfImageView((ImageView) _scene.lookup("#scene$MainMenuMarketingScreen"));
		_mainMenuMarketingScreenControl.addEvent((event) -> { _switcher.switchScene("MainMenuMarketingScreen"); });

		//entities instantiation
		_fuelCompanyEnum = new FuelCompanyEnum();
		_fuelInCompanyMotorcycleCompanyPrice = new FuelInCompany();
		_fuelInCompany = new FuelInCompany();
		_fuelEnumMotorcycleMaxPricePerType = new FuelEnum();
		_fuelInCompanySolerCompanyPrice = new FuelInCompany();
		_fuelEnumSolerMaxPricePerType = new FuelEnum();
		_fuelInCompanyBenzinCompanyPrice = new FuelInCompany();
		_fuelEnumBenzinMaxPricePerType = new FuelEnum();

		//entities assignments
		_fuelInCompanyMotorcycleCompanyPrice.setFuelCompanyEnum(_fuelCompanyEnum);
		_fuelInCompany.setFuelCompanyEnum(_fuelCompanyEnum);
		_fuelInCompany.setFuelEnum(_fuelEnumMotorcycleMaxPricePerType);
		_fuelInCompanySolerCompanyPrice.setFuelCompanyEnum(_fuelCompanyEnum);
		_fuelInCompany.setFuelEnum(_fuelEnumSolerMaxPricePerType);
		_fuelInCompanyBenzinCompanyPrice.setFuelCompanyEnum(_fuelCompanyEnum);
		_fuelInCompany.setFuelEnum(_fuelEnumBenzinMaxPricePerType);

		//controls instantiation
		_companyPriceControlMotorcycleCompanyPrice = new MfTextField((TextField) _scene.lookup("#table$fuel_company_enum$fuel_in_company$$$motorcycle$company_price"));
		_companyNameKeyControl = new MfComboBox((ComboBox) _scene.lookup("#table$fuel_company_enum$company_name_key"));
		_maxPricePerTypeControlMotorcycleMaxPricePerType = new MfText((Text) _scene.lookup("#table$fuel_company_enum$fuel_in_company$fuel_enum$$$motorcycle$max_price_per_type"));
		_companyPriceControlSolerCompanyPrice = new MfTextField((TextField) _scene.lookup("#table$fuel_company_enum$fuel_in_company$$$soler$company_price"));
		_maxPricePerTypeControlSolerMaxPricePerType = new MfText((Text) _scene.lookup("#table$fuel_company_enum$fuel_in_company$fuel_enum$$$soler$max_price_per_type"));
		_companyPriceControlBenzinCompanyPrice = new MfTextField((TextField) _scene.lookup("#table$fuel_company_enum$fuel_in_company$$$benzin$company_price"));
		_maxPricePerTypeControlBenzinMaxPricePerType = new MfText((Text) _scene.lookup("#table$fuel_company_enum$fuel_in_company$fuel_enum$$$benzin$max_price_per_type"));

		//initializations
		_updateFuelInCompanyControl = new MfImageView((ImageView) _scene.lookup("#action$update$fuel_in_company"));
		_fuelInCompanyupdateAction = new ActionControl();
		_fuelInCompanyupdateAction.setControl(_updateFuelInCompanyControl);
		UpdateCapability fuelInCompanyUpdateCapability = new UpdateCapability();
		Set<IEntity> fuelInCompanyUpdateEntities = new HashSet<IEntity>();
		fuelInCompanyUpdateCapability.setEntities(fuelInCompanyUpdateEntities);
		_fuelInCompanyupdateAction.addCapability(fuelInCompanyUpdateCapability);
		_fuelInCompanyupdateAction.setClient(_client);
		_fuelInCompanyupdateAction.setCallback((response) -> {
			
		});

		//fields initializations
		_companyPriceControlMotorcycleCompanyPrice.setField(_fuelInCompanyMotorcycleCompanyPrice.getClass().getDeclaredField("_company_price"));
		_companyPriceControlMotorcycleCompanyPrice.setEntity(_fuelInCompanyMotorcycleCompanyPrice);

		_companyNameKeyControl.setField(_fuelCompanyEnum.getClass().getDeclaredField("_company_name_key"));
		_companyNameKeyControl.setEntity(_fuelCompanyEnum);

		_maxPricePerTypeControlMotorcycleMaxPricePerType.setField(_fuelEnumMotorcycleMaxPricePerType.getClass().getDeclaredField("_max_price_per_type"));
		_maxPricePerTypeControlMotorcycleMaxPricePerType.setEntity(_fuelEnumMotorcycleMaxPricePerType);

		_companyPriceControlSolerCompanyPrice.setField(_fuelInCompanySolerCompanyPrice.getClass().getDeclaredField("_company_price"));
		_companyPriceControlSolerCompanyPrice.setEntity(_fuelInCompanySolerCompanyPrice);

		_maxPricePerTypeControlSolerMaxPricePerType.setField(_fuelEnumSolerMaxPricePerType.getClass().getDeclaredField("_max_price_per_type"));
		_maxPricePerTypeControlSolerMaxPricePerType.setEntity(_fuelEnumSolerMaxPricePerType);

		_companyPriceControlBenzinCompanyPrice.setField(_fuelInCompanyBenzinCompanyPrice.getClass().getDeclaredField("_company_price"));
		_companyPriceControlBenzinCompanyPrice.setEntity(_fuelInCompanyBenzinCompanyPrice);

		_maxPricePerTypeControlBenzinMaxPricePerType.setField(_fuelEnumBenzinMaxPricePerType.getClass().getDeclaredField("_max_price_per_type"));
		_maxPricePerTypeControlBenzinMaxPricePerType.setEntity(_fuelEnumBenzinMaxPricePerType);

		//grouping
		groupControls(new ControlAdapter[] { _maxPricePerTypeControlMotorcycleMaxPricePerType, _maxPricePerTypeControlSolerMaxPricePerType, _maxPricePerTypeControlBenzinMaxPricePerType });
		groupControls(new ControlAdapter[] { _companyPriceControlMotorcycleCompanyPrice, _companyPriceControlSolerCompanyPrice, _companyPriceControlBenzinCompanyPrice });

	}


	public FuelCompanyEnum getFuelCompanyEnum() {
		 return _fuelCompanyEnum;
	}

	public void setFuelCompanyEnum(FuelCompanyEnum fuelCompanyEnum) {
		 _fuelCompanyEnum = fuelCompanyEnum;
	}

	public FuelInCompany getFuelInCompanyMotorcycleCompanyPrice() {
		 return _fuelInCompanyMotorcycleCompanyPrice;
	}

	public void setFuelInCompanyMotorcycleCompanyPrice(FuelInCompany fuelInCompanyMotorcycleCompanyPrice) {
		 _fuelInCompanyMotorcycleCompanyPrice = fuelInCompanyMotorcycleCompanyPrice;
	}

	public FuelInCompany getFuelInCompany() {
		 return _fuelInCompany;
	}

	public void setFuelInCompany(FuelInCompany fuelInCompany) {
		 _fuelInCompany = fuelInCompany;
	}

	public FuelEnum getFuelEnumMotorcycleMaxPricePerType() {
		 return _fuelEnumMotorcycleMaxPricePerType;
	}

	public void setFuelEnumMotorcycleMaxPricePerType(FuelEnum fuelEnumMotorcycleMaxPricePerType) {
		 _fuelEnumMotorcycleMaxPricePerType = fuelEnumMotorcycleMaxPricePerType;
	}

	public FuelInCompany getFuelInCompanySolerCompanyPrice() {
		 return _fuelInCompanySolerCompanyPrice;
	}

	public void setFuelInCompanySolerCompanyPrice(FuelInCompany fuelInCompanySolerCompanyPrice) {
		 _fuelInCompanySolerCompanyPrice = fuelInCompanySolerCompanyPrice;
	}

	public FuelEnum getFuelEnumSolerMaxPricePerType() {
		 return _fuelEnumSolerMaxPricePerType;
	}

	public void setFuelEnumSolerMaxPricePerType(FuelEnum fuelEnumSolerMaxPricePerType) {
		 _fuelEnumSolerMaxPricePerType = fuelEnumSolerMaxPricePerType;
	}

	public FuelInCompany getFuelInCompanyBenzinCompanyPrice() {
		 return _fuelInCompanyBenzinCompanyPrice;
	}

	public void setFuelInCompanyBenzinCompanyPrice(FuelInCompany fuelInCompanyBenzinCompanyPrice) {
		 _fuelInCompanyBenzinCompanyPrice = fuelInCompanyBenzinCompanyPrice;
	}

	public FuelEnum getFuelEnumBenzinMaxPricePerType() {
		 return _fuelEnumBenzinMaxPricePerType;
	}

	public void setFuelEnumBenzinMaxPricePerType(FuelEnum fuelEnumBenzinMaxPricePerType) {
		 _fuelEnumBenzinMaxPricePerType = fuelEnumBenzinMaxPricePerType;
	}
}
