package wrapper;

import action.ActionControl;
import action.InsertCapability;
import annotations.AutoGenerated;
import application.Main;
import client.IClient;
import controls.MfImageView;
import db.entity.Car;
import db.entity.Customer;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.image.ImageView;
import javafx.scene.layout.BorderPane;
import sceneswitch.Context;
import sceneswitch.SceneBase;
import table.MfTable;
import widgets.table.MfAddremoveDecorator;
import widgets.table.Table;

@AutoGenerated
public class SignUpAddCarScreen extends SceneBase {

	private Customer _customer;
	private Car _car;

	private MfImageView _insertCustomerControl;
	private ActionControl _customerinsertAction;
	private MfImageView _mainMenuMarketingScreenControl;
	private MfImageView _signUpPaymentDetailsScreenControl;
	private Table<Car> _carTableWrapper;
	private MfTable<Car> _carTable;

	public SignUpAddCarScreen(ISceneSwitcher sceneSwitcher, IClient client, Context context) throws Exception {
		super(sceneSwitcher, client, context);
		initialize();
	}

	public void initialize() throws Exception {
		Parent root = FXMLLoader.load(Main.class.getResource("SignUpAddCarScreen.fxml"));
		_scene = new Scene(root);

		//scene switchers
		_mainMenuMarketingScreenControl = new MfImageView((ImageView) _scene.lookup("#scene$MainMenuMarketingScreen"));
		_mainMenuMarketingScreenControl.addEvent((event) -> { _switcher.switchScene("MainMenuMarketingScreen"); });

		_signUpPaymentDetailsScreenControl = new MfImageView((ImageView) _scene.lookup("#scene$SignUpPaymentDetailsScreen"));
		_signUpPaymentDetailsScreenControl.addEvent((event) -> { _switcher.switchScene("SignUpPaymentDetailsScreen"); });

		//entities instantiation
		_customer = new Customer();
		_car = new Car();

		//tables instantiation
		BorderPane carBp = (BorderPane) _scene.lookup("#uitable$editable$addremove$car");
		_carTableWrapper = new Table<Car>();
		_carTable = new MfTable<Car>(Car.class);
		_carTable.setEditable(true);
		MfAddremoveDecorator<Car> carAddremoveDecorator = new MfAddremoveDecorator<Car>();
		_carTableWrapper.addDecorator(carAddremoveDecorator);
		_carTableWrapper.setTable(_carTable);
		carBp.setCenter(_carTable);

		//initializations
		_insertCustomerControl = new MfImageView((ImageView) _scene.lookup("#action$insert$customer"));
		_customerinsertAction = new ActionControl();
		_customerinsertAction.setControl(_insertCustomerControl);
		InsertCapability customerInsertCapability = new InsertCapability();
		customerInsertCapability.addEntity(_customer);
		_customerinsertAction.addCapability(customerInsertCapability);
		_customerinsertAction.setClient(_client);
		_customerinsertAction.setCallback((response) -> {
			
		});


	}



}
