package wrapper;

import adapter.base.ControlAdapter;
import annotations.AutoGenerated;
import application.Main;
import client.IClient;
import controls.MfComboBox;
import controls.MfImageView;
import controls.MfPasswordField;
import controls.MfRadioButton;
import controls.MfTextField;
import db.entity.Address;
import db.entity.Customer;
import db.entity.Person;
import db.entity.SystemUser;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.ComboBox;
import javafx.scene.control.PasswordField;
import javafx.scene.control.RadioButton;
import javafx.scene.control.TextField;
import javafx.scene.image.ImageView;
import sceneswitch.Context;
import sceneswitch.SceneBase;

@AutoGenerated
public class SignUpPersonalDetailsScreen extends SceneBase {

	private Customer _customer;
	private Person _person;
	private Address _address;
	private SystemUser _systemUser;

	private MfTextField _firstNameControl;
	private MfImageView _mainMenuMarketingScreenControl;
	private MfTextField _lastNameControl;
	private MfTextField _customerIdControl;
	private MfTextField _emailControl;
	private MfTextField _phoneNumberControl;
	private MfComboBox _cityControl;
	private MfTextField _houseControl;
	private MfComboBox _streetControl;
	private MfRadioButton _customerTypeControlCompany_owner;
	private MfPasswordField _userPasswordControl;
	private MfRadioButton _customerTypeControlPrivate;
	private MfTextField _companyNameControl;
	private MfImageView _signUpPaymentDetailsScreenControl;
	private MfTextField _floorControl;
	private MfTextField _apartmentControl;

	public SignUpPersonalDetailsScreen(ISceneSwitcher sceneSwitcher, IClient client, Context context) throws Exception {
		super(sceneSwitcher, client, context);
		initialize();
	}

	public void initialize() throws Exception {
		Parent root = FXMLLoader.load(Main.class.getResource("SignUpPersonalDetailsScreen.fxml"));
		_scene = new Scene(root);

		//scene switchers
		_mainMenuMarketingScreenControl = new MfImageView((ImageView) _scene.lookup("#scene$MainMenuMarketingScreen"));
		_mainMenuMarketingScreenControl.addEvent((event) -> { _switcher.switchScene("MainMenuMarketingScreen"); });

		_signUpPaymentDetailsScreenControl = new MfImageView((ImageView) _scene.lookup("#scene$SignUpPaymentDetailsScreen"));
		_signUpPaymentDetailsScreenControl.addEvent((event) -> { _switcher.switchScene("SignUpPaymentDetailsScreen"); });

		//entities instantiation
		_customer = new Customer();
		_person = new Person();
		_address = new Address();
		_systemUser = new SystemUser();

		//entities assignments
		_customer.setPerson(_person);
		_customer.setAddress(_address);
		_customer.setSystemUser(_systemUser);

		//controls instantiation
		_firstNameControl = new MfTextField((TextField) _scene.lookup("#table$customer$person$first_name"));
		_lastNameControl = new MfTextField((TextField) _scene.lookup("#table$customer$person$last_name"));
		_customerIdControl = new MfTextField((TextField) _scene.lookup("#table$customer$customer_id"));
		_emailControl = new MfTextField((TextField) _scene.lookup("#table$customer$person$email"));
		_phoneNumberControl = new MfTextField((TextField) _scene.lookup("#table$customer$person$phone_number"));
		_cityControl = new MfComboBox((ComboBox) _scene.lookup("#table$customer$address$city"));
		_houseControl = new MfTextField((TextField) _scene.lookup("#table$customer$address$house"));
		_streetControl = new MfComboBox((ComboBox) _scene.lookup("#table$customer$address$street"));
		_customerTypeControlCompany_owner = new MfRadioButton((RadioButton) _scene.lookup("#table$customer$customer_type$$company_owner"));
		_userPasswordControl = new MfPasswordField((PasswordField) _scene.lookup("#table$customer$system_user$user_password"));
		_customerTypeControlPrivate = new MfRadioButton((RadioButton) _scene.lookup("#table$customer$customer_type$$private"));
		_companyNameControl = new MfTextField((TextField) _scene.lookup("#table$customer$company_name"));
		_floorControl = new MfTextField((TextField) _scene.lookup("#table$customer$address$floor"));
		_apartmentControl = new MfTextField((TextField) _scene.lookup("#table$customer$address$apartment"));

		//fields initializations
		_firstNameControl.setField(_person.getClass().getDeclaredField("_first_name"));
		_firstNameControl.setEntity(_person);

		_lastNameControl.setField(_person.getClass().getDeclaredField("_last_name"));
		_lastNameControl.setEntity(_person);

		_customerIdControl.setField(_customer.getClass().getDeclaredField("_customer_id"));
		_customerIdControl.setEntity(_customer);

		_emailControl.setField(_person.getClass().getDeclaredField("_email"));
		_emailControl.setEntity(_person);

		_phoneNumberControl.setField(_person.getClass().getDeclaredField("_phone_number"));
		_phoneNumberControl.setEntity(_person);

		_cityControl.setField(_address.getClass().getDeclaredField("_city"));
		_cityControl.setEntity(_address);

		_houseControl.setField(_address.getClass().getDeclaredField("_house"));
		_houseControl.setEntity(_address);

		_streetControl.setField(_address.getClass().getDeclaredField("_street"));
		_streetControl.setEntity(_address);

		_customerTypeControlCompany_owner.setField(_customer.getClass().getDeclaredField("_customer_type"));
		_customerTypeControlCompany_owner.setEntity(_customer);
		_customerTypeControlCompany_owner.setValidValue("company_owner");

		_userPasswordControl.setField(_systemUser.getClass().getDeclaredField("_user_password"));
		_userPasswordControl.setEntity(_systemUser);

		_customerTypeControlPrivate.setField(_customer.getClass().getDeclaredField("_customer_type"));
		_customerTypeControlPrivate.setEntity(_customer);
		_customerTypeControlPrivate.setValidValue("private");

		_companyNameControl.setField(_customer.getClass().getDeclaredField("_company_name"));
		_companyNameControl.setEntity(_customer);

		_floorControl.setField(_address.getClass().getDeclaredField("_floor"));
		_floorControl.setEntity(_address);

		_apartmentControl.setField(_address.getClass().getDeclaredField("_apartment"));
		_apartmentControl.setEntity(_address);

		//grouping
		groupControls(new ControlAdapter[] { _customerTypeControlCompany_owner, _customerTypeControlPrivate });

	}


	public Customer getCustomer() {
		 return _customer;
	}

	public void setCustomer(Customer customer) {
		 _customer = customer;
	}

	public Person getPerson() {
		 return _person;
	}

	public void setPerson(Person person) {
		 _person = person;
	}

	public Address getAddress() {
		 return _address;
	}

	public void setAddress(Address address) {
		 _address = address;
	}

	public SystemUser getSystemUser() {
		 return _systemUser;
	}

	public void setSystemUser(SystemUser systemUser) {
		 _systemUser = systemUser;
	}
}
