package wrapper;

import java.util.Collection;

import action.ActionControl;
import action.InsertCapability;
import annotations.AutoGenerated;
import application.Main;
import client.IClient;
import controls.MfImageView;
import db.entity.Car;
import db.entity.Customer;
import db.interfaces.IEntity;
import handler.UiHandler;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Alert.AlertType;
import javafx.scene.image.ImageView;
import javafx.scene.layout.BorderPane;
import messages.Request;
import sceneswitch.Context;
import sceneswitch.ISceneSwitcher;
import sceneswitch.SceneBase;
import table.MfTable;
import widgets.table.MfAddremoveDecorator;
import widgets.table.Table;

@AutoGenerated
public class SignUpAddCarScreen extends SceneBase {

	private Customer _customer;
	private Car _car;

	private MfImageView _insertCustomerControl;
	private ActionControl _customerinsertAction;
	private MfImageView _mainMenuMarketingScreenControl;
	private MfImageView _signUpPaymentDetailsScreenControl;
	private Table<Car> _carTableWrapper;
	private MfTable<Car> _carTable;

	public SignUpAddCarScreen(ISceneSwitcher sceneSwitcher, IClient client, Context context) throws Exception {
		super(sceneSwitcher, client, context);
	}

	@Override
	public void initialize() throws Exception {
		Parent root = FXMLLoader.load(Main.class.getResource("SignUpAddCarScreen.fxml"));
		_scene = new Scene(root);

		//scene switchers
		_mainMenuMarketingScreenControl = new MfImageView((ImageView) _scene.lookup("#scene$MainMenuMarketingScreen"));
		_mainMenuMarketingScreenControl.addEvent((event) -> { _switcher.switchScene("MainMenuMarketingScreen"); });

		_signUpPaymentDetailsScreenControl = new MfImageView((ImageView) _scene.lookup("#scene$SignUpPaymentDetailsScreen"));
		_signUpPaymentDetailsScreenControl.addEvent((event) -> { 
			_switcher.switchScene("SignUpPaymentDetailsScreen"); 
			});

		//entities instantiation
		if (_customer == null) {
			_customer = new Customer();
		}
		if (_car == null) {
			_car = new Car();
		}
		_car.setCustomer(_customer);

		//tables instantiation
		BorderPane carBp = (BorderPane) _scene.lookup("#uitable$editable$addremove$car");
		_carTableWrapper = new Table<Car>();
		_carTable = new MfTable<Car>(Car.class);
		_carTable.setEditable(true);
		MfAddremoveDecorator<Car> carAddremoveDecorator = new MfAddremoveDecorator<Car>();
		_carTableWrapper.addDecorator(carAddremoveDecorator);
		_carTableWrapper.setTable(_carTable);
		carBp.setCenter(_carTable);

		//initializations
		_insertCustomerControl = new MfImageView((ImageView) _scene.lookup("#action$insert$customer"));
		_insertCustomerControl.
			setMouseImages("@resource/images/Finish_btn.png", "@resource/images/Finish_overbtn.png", "@resource/images/Finish_clickbtn.png");
		_customerinsertAction = new ActionControl();
		_customerinsertAction.setControl(_insertCustomerControl);
		InsertCapability customerInsertCapability = new InsertCapability();
		customerInsertCapability.setEntities(carAddremoveDecorator.getEntities());
		_customerinsertAction.addCapability(customerInsertCapability);
		_customerinsertAction.setClient(_client);
		_customerinsertAction.setPreSend((request) -> {
			Collection<IEntity> entities = ((Request) request).getEntities();
			for (IEntity entity : entities) {
				((Car) entity).setCustomer(_customer);
			}
			return true;
		});
		_customerinsertAction.setCallback((response) -> {
			if (response.isPassed()) {
				UiHandler.showAlert(AlertType.INFORMATION, "Cars Update", "", "Cars Were Added");
			}
			else {
				UiHandler.showAlert(AlertType.ERROR, "Cars Update", "", response.getDescription());
			}
		});


	}

	@Override
	protected void onLoad() {
		
	}

	@Override
	public void setParameters(IEntity[] entities) {
		super.setParameters(entities);
		if (entities != null && entities.length > 0) {
			_customer = (Customer) entities[0];
		}
	}



}
