package wrapper;

import javafx.scene.layout.BorderPane;
import javafx.fxml.FXMLLoader;
import adapter.base.ControlAdapter;
import java.util.HashSet;
import widgets.table.Table;
import controls.*;
import annotations.AutoGenerated;
import java.util.HashMap;
import javafx.scene.Parent;
import sceneswitch.SceneBase;
import table.MfTable;
import widgets.table.*;
import javafx.scene.Scene;
import javafx.scene.control.*;
import action.*;
import db.interfaces.IEntity;
import javafx.scene.image.ImageView;
import java.util.Set;
import javafx.scene.text.Text;

@AutoGenerated
public class SignUpPaymentDetailsScreen extends SceneBase {

	public SignUpPaymentDetailsScreen(ISceneSwitcher sceneSwitcher) {
		super(sceneSwitcher);
	}

	public void initialize() {
		Parent root = FXMLLoader.load(getClass().getResource("SignUpPaymentDetailsScreen.fxml"));
		_scene = new Scene(root);

		//entities instantiation
		Customer customer = new Customer();
		Payment payment = new Payment();

		//controls instantiation
		MfTextField creditCardNumberControl = new MfTextField((TextField) _scene.lookup("#table$customer$payment$credit_card_number"));
		MfTextField expirationDateMonthControl = new MfTextField((TextField) _scene.lookup("#table$customer$payment$expiration_date_month"));
		MfTextField expirationDateYearControl = new MfTextField((TextField) _scene.lookup("#table$customer$payment$expiration_date_year"));
		MfTextField cvvControl = new MfTextField((TextField) _scene.lookup("#table$customer$payment$cvv"));
		MfCheckBox cashControl = new MfCheckBox((CheckBox) _scene.lookup("#table$customer$payment$cash"));

		//initializations
		MfHyperlink mainMenuMarketingScreenControl = new MfHyperlink((Hyperlink) _scene.lookup("#scene$MainMenuMarketingScreen"));
		mainMenuMarketingScreenControl.addEvent((event) -> { _switcher.switchScene("MainMenuMarketingScreen"); });
		customer.setPayment(payment);
		MfImageView signUpAddCarScreenControl = new MfImageView((ImageView) _scene.lookup("#scene$SignUpAddCarScreen"));
		signUpAddCarScreenControl.addEvent((event) -> { _switcher.switchScene("SignUpAddCarScreen"); });
		MfImageView mainMenuMarketingScreenControl = new MfImageView((ImageView) _scene.lookup("#scene$MainMenuMarketingScreen"));
		mainMenuMarketingScreenControl.addEvent((event) -> { _switcher.switchScene("MainMenuMarketingScreen"); });
		MfImageView signUpPersonalDetailsScreenControl = new MfImageView((ImageView) _scene.lookup("#scene$SignUpPersonalDetailsScreen"));
		signUpPersonalDetailsScreenControl.addEvent((event) -> { _switcher.switchScene("SignUpPersonalDetailsScreen"); });

		//fields initializations
		creditCardNumberControl.setField(payment.getClass().getField("_credit_card_number"));
		creditCardNumberControl.setEntity(payment);

		expirationDateMonthControl.setField(payment.getClass().getField("_expiration_date_month"));
		expirationDateMonthControl.setEntity(payment);

		expirationDateYearControl.setField(payment.getClass().getField("_expiration_date_year"));
		expirationDateYearControl.setEntity(payment);

		cvvControl.setField(payment.getClass().getField("_cvv"));
		cvvControl.setEntity(payment);

		cashControl.setField(payment.getClass().getField("_cash"));
		cashControl.setEntity(payment);

		//grouping

	}

}
