package wrapper;

import annotations.AutoGenerated;
import application.Main;
import client.IClient;
import controls.MfCheckBox;
import controls.MfImageView;
import controls.MfTextField;
import db.entity.Customer;
import db.entity.Payment;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.CheckBox;
import javafx.scene.control.TextField;
import javafx.scene.image.ImageView;
import sceneswitch.Context;
import sceneswitch.SceneBase;

@AutoGenerated
public class SignUpPaymentDetailsScreen extends SceneBase {

	private Customer _customer;
	private Payment _payment;

	private MfTextField _creditCardNumberControl;
	private MfImageView _signUpAddCarScreenControl;
	private MfTextField _expirationDateMonthControl;
	private MfTextField _expirationDateYearControl;
	private MfTextField _cvvControl;
	private MfCheckBox _cashControl;
	private MfImageView _mainMenuMarketingScreenControl;
	private MfImageView _signUpPersonalDetailsScreenControl;

	public SignUpPaymentDetailsScreen(ISceneSwitcher sceneSwitcher, IClient client, Context context) throws Exception {
		super(sceneSwitcher, client, context);
		initialize();
	}

	public void initialize() throws Exception {
		Parent root = FXMLLoader.load(Main.class.getResource("SignUpPaymentDetailsScreen.fxml"));
		_scene = new Scene(root);

		//scene switchers
		_signUpAddCarScreenControl = new MfImageView((ImageView) _scene.lookup("#scene$SignUpAddCarScreen"));
		_signUpAddCarScreenControl.addEvent((event) -> { _switcher.switchScene("SignUpAddCarScreen"); });

		_mainMenuMarketingScreenControl = new MfImageView((ImageView) _scene.lookup("#scene$MainMenuMarketingScreen"));
		_mainMenuMarketingScreenControl.addEvent((event) -> { _switcher.switchScene("MainMenuMarketingScreen"); });

		_signUpPersonalDetailsScreenControl = new MfImageView((ImageView) _scene.lookup("#scene$SignUpPersonalDetailsScreen"));
		_signUpPersonalDetailsScreenControl.addEvent((event) -> { _switcher.switchScene("SignUpPersonalDetailsScreen"); });

		//entities instantiation
		_customer = new Customer();
		_payment = new Payment();

		//entities assignments
		_customer.setPayment(_payment);

		//controls instantiation
		_creditCardNumberControl = new MfTextField((TextField) _scene.lookup("#table$customer$payment$credit_card_number"));
		_expirationDateMonthControl = new MfTextField((TextField) _scene.lookup("#table$customer$payment$expiration_date_month"));
		_expirationDateYearControl = new MfTextField((TextField) _scene.lookup("#table$customer$payment$expiration_date_year"));
		_cvvControl = new MfTextField((TextField) _scene.lookup("#table$customer$payment$cvv"));
		_cashControl = new MfCheckBox((CheckBox) _scene.lookup("#table$customer$payment$cash"));

		//fields initializations
		_creditCardNumberControl.setField(_payment.getClass().getDeclaredField("_credit_card_number"));
		_creditCardNumberControl.setEntity(_payment);

		_expirationDateMonthControl.setField(_payment.getClass().getDeclaredField("_expiration_date_month"));
		_expirationDateMonthControl.setEntity(_payment);

		_expirationDateYearControl.setField(_payment.getClass().getDeclaredField("_expiration_date_year"));
		_expirationDateYearControl.setEntity(_payment);

		_cvvControl.setField(_payment.getClass().getDeclaredField("_cvv"));
		_cvvControl.setEntity(_payment);

		_cashControl.setField(_payment.getClass().getDeclaredField("_cash"));
		_cashControl.setEntity(_payment);


	}


	public Customer getCustomer() {
		 return _customer;
	}

	public void setCustomer(Customer customer) {
		 _customer = customer;
	}

	public Payment getPayment() {
		 return _payment;
	}

	public void setPayment(Payment payment) {
		 _payment = payment;
	}
}
