package wrapper;

import javafx.scene.layout.BorderPane;
import javafx.fxml.FXMLLoader;
import adapter.base.ControlAdapter;
import java.util.HashSet;
import widgets.table.Table;
import controls.*;
import annotations.AutoGenerated;
import java.util.HashMap;
import javafx.scene.Parent;
import sceneswitch.SceneBase;
import table.MfTable;
import widgets.table.*;
import javafx.scene.Scene;
import javafx.scene.control.*;
import action.*;
import db.interfaces.IEntity;
import javafx.scene.image.ImageView;
import java.util.Set;
import javafx.scene.text.Text;

@AutoGenerated
public class SignUpAddCarScreen extends SceneBase {

	public SignUpAddCarScreen(ISceneSwitcher sceneSwitcher) {
		super(sceneSwitcher);
	}

	public void initialize() {
		Parent root = FXMLLoader.load(getClass().getResource("SignUpAddCarScreen.fxml"));
		_scene = new Scene(root);

		//entities instantiation


		//controls instantiation


		//initializations
		MfHyperlink mainMenuMarketingScreenControl = new MfHyperlink((Hyperlink) _scene.lookup("#scene$MainMenuMarketingScreen"));
		mainMenuMarketingScreenControl.addEvent((event) -> { _switcher.switchScene("MainMenuMarketingScreen"); });
		MfImageView customerControl = new MfImageView((ImageView) _scene.lookup("#action$insert$customer"));
		ActionControl insertAction = new ActionControl();
		insertAction.setControl(customerControl);
		InsertCapability customerInsertCapability = new InsertCapability();
		customerInsertCapability.addEntity(customer);
		insertAction.addCapability(customerInsertCapability);
		insertAction.setCallback((response) -> {});
		MfImageView mainMenuMarketingScreenControl = new MfImageView((ImageView) _scene.lookup("#scene$MainMenuMarketingScreen"));
		mainMenuMarketingScreenControl.addEvent((event) -> { _switcher.switchScene("MainMenuMarketingScreen"); });
		MfImageView signUpPaymentDetailsScreenControl = new MfImageView((ImageView) _scene.lookup("#scene$SignUpPaymentDetailsScreen"));
		signUpPaymentDetailsScreenControl.addEvent((event) -> { _switcher.switchScene("SignUpPaymentDetailsScreen"); });
		BorderPane carBp = (BorderPane) _scene.lookup("#uitable$editable$addremove$car");
		Table<Car> carTableWrapper = new Table<Car>();
		MfTable<Car> carTable = new MfTable<Car>(Car.class);
		carTable.setEditable(true);
		MfAddremoveCapability<Car> carAddremoveCapability = new MfAddremoveCapability<Car>();
		carTableWrapper.addCapability(carAddremoveCapability);
		carTableWrapper.setTable(carTable);
		carBp.setCenter(carTable.getInstance());

		//fields initializations


		//grouping

	}

}
