package wrapper;

import java.util.HashSet;
import java.util.Set;

import action.ActionControl;
import action.UpdateCapability;
import annotations.AutoGenerated;
import application.Main;
import client.IClient;
import controls.MfImageView;
import controls.MfText;
import db.entity.Employee;
import db.entity.FuelEnum;
import db.entity.Station;
import db.entity.StationSupplyOrder;
import db.entity.StationsFuel;
import db.interfaces.IEntity;
import enums.Enums;
import handler.UiHandler;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Alert.AlertType;
import javafx.scene.image.ImageView;
import javafx.scene.text.Text;
import sceneswitch.Context;
import sceneswitch.ISceneSwitcher;
import sceneswitch.SceneBase;

@AutoGenerated
public class SupplyOrderConfirmationPopScreen extends SceneBase {

	private StationSupplyOrder _stationSupplyOrder;
	private Station _station;
	private StationsFuel _stationsFuel;
	private FuelEnum _fuelEnum;

	private MfImageView _updateStationSupplyOrderControl;
	private ActionControl _stationSupplyOrderupdateAction;
	private MfImageView _ordersStationManagerScreenControl;
	private MfText _orderIdControl;
	private MfText _fuelEnumControl;
	private MfText _amountControl;
	private MfText _stationNameControl;
	private MfText _addressControl;
	private MfText _currentAmountControl;
	
	private Set<IEntity> _stationSupplyOrderUpdateEntities;

	public SupplyOrderConfirmationPopScreen(ISceneSwitcher sceneSwitcher, IClient client, Context context) throws Exception {
		super(sceneSwitcher, client, context);
	}

	@Override
	public void initialize() throws Exception {
		Parent root = FXMLLoader.load(Main.class.getResource("SupplyOrderConfirmationPopScreen.fxml"));
		_scene = new Scene(root);

		//scene switchers
		_ordersStationManagerScreenControl = new MfImageView((ImageView) _scene.lookup("#scene$FuelOrderManagementScreen"));
		_ordersStationManagerScreenControl.addEvent((event) -> { _switcher.switchScene("FuelOrderManagementScreen"); });

		//entities instantiation
		if (_stationSupplyOrder == null) {
			_stationSupplyOrder = new StationSupplyOrder();
		}
		if (_stationsFuel == null) {
			_stationsFuel = new StationsFuel();
		}
		_station = _context.getEmployee().getStation();

		//entities assignments
		_stationSupplyOrder.setStation(_station);
		_stationsFuel.setStation(_station);
		_fuelEnum = _client.getEnum(FuelEnum.class, _stationSupplyOrder.getFuelEnum().getId());

		//controls instantiation
		_orderIdControl = new MfText((Text) _scene.lookup("#table$station$station_supply_order$id"));
		_fuelEnumControl = new MfText((Text) _scene.lookup("#table$station$station_supply_order$fuel_enum"));
		_amountControl = new MfText((Text) _scene.lookup("#table$station$station_supply_order$amount"));
		_stationNameControl = new MfText((Text) _scene.lookup("#table$station$station_name"));
		_addressControl = new MfText((Text) _scene.lookup("#table$station$address"));
		_currentAmountControl = new MfText((Text) _scene.lookup("#table$station$stations_fuel$current_amount"));

		//initializations
		_updateStationSupplyOrderControl = new MfImageView((ImageView) _scene.lookup("#action$update$station_supply_order"));
		_updateStationSupplyOrderControl.
			setMouseImages("@resource/images/Confirm_btn.jpg", "@resource/images/Confirm_overbtn.png", "@resource/images/Confirm_clickbtn.png");
		_stationSupplyOrderupdateAction = new ActionControl();
		_stationSupplyOrderupdateAction.setControl(_updateStationSupplyOrderControl);
		UpdateCapability stationSupplyOrderUpdateCapability = new UpdateCapability();
		_stationSupplyOrderUpdateEntities = new HashSet<IEntity>();
		_stationSupplyOrderUpdateEntities.add(_stationSupplyOrder);
		stationSupplyOrderUpdateCapability.setEntities(_stationSupplyOrderUpdateEntities);
		_stationSupplyOrderupdateAction.addCapability(stationSupplyOrderUpdateCapability);
		_stationSupplyOrderupdateAction.setClient(_client);
		_stationSupplyOrderupdateAction.setPreSend((request) -> {
			_stationSupplyOrder.setOrderStatus(Enums.InProcess);
			return true;
		});
		_stationSupplyOrderupdateAction.setCallback((response) -> {
			if (!response.isPassed()) {
				UiHandler.showAlert(AlertType.ERROR, "Station Supply Order Status Change", "", response.getDescription());
			}
			else {
				_switcher.switchScene("FuelOrderManagementScreen");
			}
		});

		//fields initializations
		_orderIdControl.setField(_stationSupplyOrder.getClass().getDeclaredField("_id"));
		_orderIdControl.setEntity(_stationSupplyOrder);

		_fuelEnumControl.setField(_fuelEnum.getClass().getDeclaredField("_fuel_type_key"));
		_fuelEnumControl.setEntity(_fuelEnum);

		_amountControl.setField(_stationSupplyOrder.getClass().getDeclaredField("_amount"));
		_amountControl.setEntity(_stationSupplyOrder);

		_stationNameControl.setField(_station.getClass().getDeclaredField("_station_name"));
		_stationNameControl.setEntity(_station);

		_addressControl.setField(_station.getClass().getDeclaredField("_address"));
		_addressControl.setEntity(_station);

		_currentAmountControl.setField(_stationsFuel.getClass().getDeclaredField("_current_amount"));
		_currentAmountControl.setEntity(_stationsFuel);


	}

	@Override
	protected void onLoad() {
		
	}

	@Override
	public void setParameters(IEntity[] entities) {
		super.setParameters(entities);
		if (entities.length > 0) {
			_stationSupplyOrder = (StationSupplyOrder) entities[0];
		}
		if (_context.getEmployee() == null) {
			Employee employee = new Employee();
			Station station = new Station();
			station.setId(1);
			_context.setEmployee(employee);
		}
	}


	public Station getStation() {
		 return _station;
	}

	public void setStation(Station station) {
		 _station = station;
	}

	public StationSupplyOrder getStationSupplyOrder() {
		 return _stationSupplyOrder;
	}

	public void setStationSupplyOrder(StationSupplyOrder stationSupplyOrder) {
		 _stationSupplyOrder = stationSupplyOrder;
	}

	public StationsFuel getStationsFuel() {
		 return _stationsFuel;
	}

	public void setStationsFuel(StationsFuel stationsFuel) {
		 _stationsFuel = stationsFuel;
	}
}
