package wrappers.tmp;

import java.util.Collection;
import java.util.HashMap;
import java.util.Map;

import action.ActionControl;
import action.FilterCapability;
import adapter.base.ControlAdapter;
import annotations.AutoGenerated;
import application.Main;
import client.IClient;
import controls.MfComboBox;
import controls.MfImageView;
import controls.MfText;
import db.entity.FuelEnum;
import db.entity.Station;
import db.entity.StationManagerReports;
import db.entity.StationSupplyOrder;
import db.interfaces.IEntity;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.ComboBox;
import javafx.scene.image.ImageView;
import javafx.scene.text.Text;
import sceneswitch.SceneBase;

@AutoGenerated
public class ExpenseReportScreen extends SceneBase {

	public ExpenseReportScreen(ISceneSwitcher sceneSwitcher, IClient client) throws Exception {
		super(sceneSwitcher, client);
		initialize();
	}

	public void initialize() throws Exception {
		Parent root = FXMLLoader.load(Main.class.getResource("ExpenseReportScreen.fxml"));
		_scene = new Scene(root);

		//scene switchers
		MfImageView mainMenuStationManagerScreenControl = new MfImageView((ImageView) _scene.lookup("#scene$MainMenuStationManagerScreen"));
		mainMenuStationManagerScreenControl.addEvent((event) -> { _switcher.switchScene("MainMenuStationManagerScreen"); });

		//entities instantiation
		StationManagerReports stationManagerReports = new StationManagerReports();
		Station station = new Station();
		StationSupplyOrder stationSupplyOrder = new StationSupplyOrder();
		FuelEnum fuelEnum = new FuelEnum();

		//entities assignments
		stationManagerReports.setStation(station);
		stationSupplyOrder.setStation(station);
		stationSupplyOrder.setFuelEnum(fuelEnum);

		//controls instantiation
		MfText reportDateControlTxt = new MfText((Text) _scene.lookup("#table$station_manager_reports$report_date$$$txt"));
		MfText stationNameControl = new MfText((Text) _scene.lookup("#table$station_manager_reports$station$station_name"));
		MfText amountControlBenzinAmount = new MfText((Text) _scene.lookup("#table$station_manager_reports$station$station_supply_order$fuel_enum$$$benzin$amount"));
		MfText amountControlSolerAmount = new MfText((Text) _scene.lookup("#table$station_manager_reports$station$station_supply_order$fuel_enum$$$soler$amount"));
		MfText amountControlMotorcycleAmount = new MfText((Text) _scene.lookup("#table$station_manager_reports$station$station_supply_order$fuel_enum$$$motorcycle$amount"));
		MfText totalPriceControlBenzinTotal_price = new MfText((Text) _scene.lookup("#table$station_manager_reports$station$station_supply_order$fuel_enum$$$benzin$total_price"));
		MfText totalPriceControlSolerTotal_price = new MfText((Text) _scene.lookup("#table$station_manager_reports$station$station_supply_order$fuel_enum$$$soler$total_price"));
		MfText totalPriceControlMotorcycleTotal_price = new MfText((Text) _scene.lookup("#table$station_manager_reports$station$station_supply_order$fuel_enum$$$motorcycle$total_price"));
		MfComboBox reportDateControlCmb = new MfComboBox((ComboBox) _scene.lookup("#table$station_manager_reports$report_date$$$cmb"));

		//initializations
		MfImageView filterStationManagerReportsControl = new MfImageView((ImageView) _scene.lookup("#action$collect$station_manager_reports"));
		ActionControl stationManagerReportsfilterAction = new ActionControl();
		stationManagerReportsfilterAction.setControl(filterStationManagerReportsControl);
		FilterCapability stationManagerReportsFilterCapability = new FilterCapability();
		stationManagerReportsFilterCapability.setQueryEntities(prepareQuery(stationManagerReports));
		stationManagerReportsfilterAction.addCapability(stationManagerReportsFilterCapability);
		stationManagerReportsfilterAction.setClient(_client);
		stationManagerReportsfilterAction.setCallback((response) -> {
			Collection<IEntity> entities = response.getEntities();
			for (IEntity ientity : entities) {
				StationManagerReports entity = (StationManagerReports) ientity;
			}
		});

		//fields initializations
		reportDateControlTxt.setField(stationManagerReports.getClass().getDeclaredField("_report_date"));
		reportDateControlTxt.setEntity(stationManagerReports);

		stationNameControl.setField(station.getClass().getDeclaredField("_station_name"));
		stationNameControl.setEntity(station);

		amountControlBenzinAmount.setField(fuelEnum.getClass().getDeclaredField("_amount"));
		amountControlBenzinAmount.setEntity(fuelEnum);

		amountControlSolerAmount.setField(fuelEnum.getClass().getDeclaredField("_amount"));
		amountControlSolerAmount.setEntity(fuelEnum);

		amountControlMotorcycleAmount.setField(fuelEnum.getClass().getDeclaredField("_amount"));
		amountControlMotorcycleAmount.setEntity(fuelEnum);

		totalPriceControlBenzinTotal_price.setField(fuelEnum.getClass().getDeclaredField("_total_price"));
		totalPriceControlBenzinTotal_price.setEntity(fuelEnum);

		totalPriceControlSolerTotal_price.setField(fuelEnum.getClass().getDeclaredField("_total_price"));
		totalPriceControlSolerTotal_price.setEntity(fuelEnum);

		totalPriceControlMotorcycleTotal_price.setField(fuelEnum.getClass().getDeclaredField("_total_price"));
		totalPriceControlMotorcycleTotal_price.setEntity(fuelEnum);

		reportDateControlCmb.setField(stationManagerReports.getClass().getDeclaredField("_report_date"));
		reportDateControlCmb.setEntity(stationManagerReports);

		//grouping
		groupControls(new ControlAdapter[] { reportDateControlTxt, reportDateControlCmb });
		groupControls(new ControlAdapter[] { amountControlBenzinAmount, amountControlSolerAmount, amountControlMotorcycleAmount });
		groupControls(new ControlAdapter[] { totalPriceControlBenzinTotal_price, totalPriceControlSolerTotal_price, totalPriceControlMotorcycleTotal_price });

	}
	private Map<IEntity, Map<String, String>> prepareQuery(StationManagerReports stationManagerReports) {
		Map<IEntity, Map<String, String>> map = new HashMap<IEntity, Map<String, String>>();
		
		Map<String, String> queryMap = new HashMap<String, String>();
		
		map.put(stationManagerReports, queryMap);
		return map;
	}
}
